{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.6-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2.jar",
          "size": 17478,
          "sha512": "5fef77a3b601527b6ddac532933d14d4898498a41f37c9b104e15716c3cf0af41f331e37f2f37d05e8787d73019d97c25f51d8c7eeb5c97508920fb294ce0888",
          "sha256": "e2aebc227254c4f66027f3a7f2a45929bb83645e3b6c3f7156f2c4a4364d0448",
          "sha1": "42e7b9fc2adc03156ee1e20a40ed727edacf6d0e",
          "md5": "5435da82f4d24126ec8ba27c0b8c4596"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2.jar",
          "size": 17478,
          "sha512": "5fef77a3b601527b6ddac532933d14d4898498a41f37c9b104e15716c3cf0af41f331e37f2f37d05e8787d73019d97c25f51d8c7eeb5c97508920fb294ce0888",
          "sha256": "e2aebc227254c4f66027f3a7f2a45929bb83645e3b6c3f7156f2c4a4364d0448",
          "sha1": "42e7b9fc2adc03156ee1e20a40ed727edacf6d0e",
          "md5": "5435da82f4d24126ec8ba27c0b8c4596"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2-sources.jar",
          "size": 11739,
          "sha512": "0612a717fe90f68e26eafb9ba210139467ce390c2d074c47f717c95e7daea962e7db5b8847cd287677a0e117e04dc6354c244d46fd1e8e0691352f6ffff580e1",
          "sha256": "0f1c951662534df1b391e165b2c71a58095826297c0c571001e2c56b0a619989",
          "sha1": "0b0f0a6b31321c5d5087b53c896d1b8588445d63",
          "md5": "3015668edb72abab357dff316a1a6547"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha2-javadoc.jar",
          "size": 123848,
          "sha512": "cce23b7022e057e9308924128239bfc3d8e1b6dcfe3e6557f74a394c311719028775b9a240ac4ff9ef05551497314e01d404b9dd6d98ecba1e37f2453a06550b",
          "sha256": "0b719bdcb713c3581d2e481689714c5cff0ee416cbbadbf0f7807517074f2d67",
          "sha1": "34282f5705f661d27a2cb0b0af9f1c7379ddfad1",
          "md5": "31098f40ff027ca5c1a53f8dfdadf325"
        }
      ]
    }
  ]
}
