{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.3-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1.jar",
          "size": 11541,
          "sha512": "dcc0182ec06ddb5a16eee1767354ae22e8890ef13fa31c0ccd3e4df568cf1a5b29e1e4524cf5b34e2c85615679d47e7bc2adc8d4cef2a6e6a9a3538903343281",
          "sha256": "036ca9876777b58ce96b31f1bbabf61256104a00484aebc538bdca33cb9cbe59",
          "sha1": "5a07d53bb31cd81b65c579f3016b1d180a41118c",
          "md5": "b211e2decdd3d5eb2cde075fe7094f01"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1.jar",
          "size": 11541,
          "sha512": "dcc0182ec06ddb5a16eee1767354ae22e8890ef13fa31c0ccd3e4df568cf1a5b29e1e4524cf5b34e2c85615679d47e7bc2adc8d4cef2a6e6a9a3538903343281",
          "sha256": "036ca9876777b58ce96b31f1bbabf61256104a00484aebc538bdca33cb9cbe59",
          "sha1": "5a07d53bb31cd81b65c579f3016b1d180a41118c",
          "md5": "b211e2decdd3d5eb2cde075fe7094f01"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1-sources.jar",
          "size": 9440,
          "sha512": "7aa1ae60fdd332e9273480eacf785fb243574d03713baf955b6c05948020f79bf5f9813caebc15fd233c77a6b1909cfeccafa5d0b7d743772b06672dc124c60a",
          "sha256": "7a7c460a71ce6a8d9064a645344f906c785afb9606f3004f259ef9ad677ad765",
          "sha1": "4f21d2b9c9ed4db7495682588f1670024ece840e",
          "md5": "a82bceb0999982db47463f607909fb67"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha1-javadoc.jar",
          "size": 108727,
          "sha512": "7b8c9d53b0c72b95defda2df0a03bdba6712b825924f7eb300303ac770d83277c832c359c3d265a574ba28f272e1a446a21ffbaa18239d64e9e08ffb22c2b4b1",
          "sha256": "d5db4e66637fe8072489ee5693ebe8b2e29f738fbadb88a4d6faa48cc0a7cfe6",
          "sha1": "e03ae7cac21f69b3740041a540f1bccc4b265ff9",
          "md5": "479ab38bc903cd48bf8ea46cd8cdae52"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    }
  ]
}
