{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.6-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-alpha1.jar",
          "size": 11769,
          "sha512": "c9dac3c51279878c95181b11c2ec7a0982eec0361c9624c75213d1b8df985381267c807e1db9ced1339e02b070c9c633146c42734aad9776f7bb2e6b6fdec6ae",
          "sha256": "487af09b56c5ff6b1a38463a7daba8e0c9bd876c7c4d0b9075b8d90722b8288d",
          "sha1": "bda6d6586d1071c4efb74dac39cbed87808bc347",
          "md5": "8cd778ef2fc4c6bfc78cb9d05fbce9cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-alpha1.jar",
          "size": 11769,
          "sha512": "c9dac3c51279878c95181b11c2ec7a0982eec0361c9624c75213d1b8df985381267c807e1db9ced1339e02b070c9c633146c42734aad9776f7bb2e6b6fdec6ae",
          "sha256": "487af09b56c5ff6b1a38463a7daba8e0c9bd876c7c4d0b9075b8d90722b8288d",
          "sha1": "bda6d6586d1071c4efb74dac39cbed87808bc347",
          "md5": "8cd778ef2fc4c6bfc78cb9d05fbce9cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-alpha1-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-alpha1-sources.jar",
          "size": 7816,
          "sha512": "3e299cc0744a665ae6fa98efd87b38690c9737a55785ff92470c128b69d1bd47c344322f5563cf0d6628c9f752da6ade754541d11818d9be122909a76577cecc",
          "sha256": "626978a82b77aeca9f258b78a627343abc3a09aa576112d57318f7007b4c694d",
          "sha1": "d174ff98d7141812996f1ea756df9c82fd53edd2",
          "md5": "e2d0c43e77a95b9355ef2cb6326e05de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "size": 114617,
          "sha512": "695b2ca57989c4586acede0e430a4732a9c095d6b717cf0fc6fef29310246a2fec62ec2df1575860628b30d0bef744bb5490a742b5094e4d0377a35a6eb0bf51",
          "sha256": "b73259778d5f02981de04e8380a7fde1e56720f0b7fe45799689c33006f04ecc",
          "sha1": "f0ad8578bcd5a058dbdc1293ed4befcd2912db88",
          "md5": "4a26b237c264b6471e87e73ba1ea2e82"
        }
      ]
    }
  ]
}
