{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.4-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta2.jar",
          "size": 13535,
          "sha512": "bfb36e9ddda7026068316f4a6091c9db216ec30ea467d9c546aa7e9939edb555337d232ac7cd8f807de4f25da5ddc7825462c177993bb55d541993963851407e",
          "sha256": "7ecbbeec8174f25198e2deb572aebeac4559e2deac2a1b89c2e45cb354655596",
          "sha1": "295a654c90b521527c7463f2f0f9133b58615af7",
          "md5": "49ad0d4fe92fb56638506663bcfb0617"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta2.jar",
          "size": 13535,
          "sha512": "bfb36e9ddda7026068316f4a6091c9db216ec30ea467d9c546aa7e9939edb555337d232ac7cd8f807de4f25da5ddc7825462c177993bb55d541993963851407e",
          "sha256": "7ecbbeec8174f25198e2deb572aebeac4559e2deac2a1b89c2e45cb354655596",
          "sha1": "295a654c90b521527c7463f2f0f9133b58615af7",
          "md5": "49ad0d4fe92fb56638506663bcfb0617"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta2-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta2-sources.jar",
          "size": 9757,
          "sha512": "d5f1707c33f9df5f49f6ea3f65fadd58c7fca23848935121847d9d35e0dd4453c31ca4217258e4d68784ce2d330d17583f4752a9e08e7acde580c8f17505bed4",
          "sha256": "a99a8a4a6aa8f3d34f03a5e6f2f7f580ddeeea3a64c01042ecca9dd2e164dfe2",
          "sha1": "557c2bcc374c66b300e457a29cf96c380434513b",
          "md5": "4fe6b6684907a7bced9aac581d565754"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta2-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta2-javadoc.jar",
          "size": 114202,
          "sha512": "3855f4d4fab35b94cca8b7ff4aed784640a7e95bac0c4a3d39d1f5591b34a55a4b99930f5a30f0e21a31382b4c940078df696cb24a701ef6d1122a5738acf3d6",
          "sha256": "98354202c549d09d9f56086a25bf556cd6565b143c0baf322f5d2fb88d5f3387",
          "sha1": "386a6881d6c79d46f1fb9e5929329f27139bc121",
          "md5": "28f01081d5d0132a7866f386b820c09b"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta2-accesstransformer.cfg",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta2-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
