{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.3-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha2.jar",
          "size": 7720,
          "sha512": "4e765026bf82c50bea6221730e0f19e632a8a5c274f07b86928132f9624b31ad4a2ed20b5865d5eb07171685e7d9d1f1598394ba15f53fd1b9ecec2f385c4ba8",
          "sha256": "0286c6310fdb533ee41c26d8661e1d458200b44a2fa0be56ec5080c281dae0d8",
          "sha1": "e15883caab7b5f1341329a39df033ff31c9c8ec6",
          "md5": "131599d121284171cf646bcbb90b349f"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha2.jar",
          "size": 7720,
          "sha512": "4e765026bf82c50bea6221730e0f19e632a8a5c274f07b86928132f9624b31ad4a2ed20b5865d5eb07171685e7d9d1f1598394ba15f53fd1b9ecec2f385c4ba8",
          "sha256": "0286c6310fdb533ee41c26d8661e1d458200b44a2fa0be56ec5080c281dae0d8",
          "sha1": "e15883caab7b5f1341329a39df033ff31c9c8ec6",
          "md5": "131599d121284171cf646bcbb90b349f"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha2-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha2-sources.jar",
          "size": 6261,
          "sha512": "acab1a5585774dcc6114a3e7624d264b5e20df807c55b3869ecc76f67a43f6ab5d19bc17e83cc96f55579f229fd5a2ddf80342a2dc82154111ea68fd9b7b44f7",
          "sha256": "0f762f9892cc7ad3a3a1d4c31314166525331fcaeb50f1968087a129d0e6a174",
          "sha1": "ecd4af683230009fe0ad122a5c56627035f67443",
          "md5": "541e57909d71525bc0bbe6a70f176987"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha2-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha2-javadoc.jar",
          "size": 100692,
          "sha512": "6188a0fa96bf6507e48303e1e8fa579a75b78ab11b0bc94e88f2f03d1873eebcce59832ecbb1188eb1cf382921c65d35ea10afbda3f848884ac84f48df38c322",
          "sha256": "38267a69d58a013e2b59f21c554eaed64a594b866060223eb34d14544f338891",
          "sha1": "8c835dbefbc817ba3018d331ebf8999d7d46f388",
          "md5": "8c3be699ed23f02bc703b866e2e15752"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    }
  ]
}
