{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.2.jar",
          "size": 7714,
          "sha512": "4627658c56e80b582b90e199f02f23a9585e943cd9b82c0f3d9739555af3ce7d6985c852e86ce7880f19c2586b942af5da184ace1b9a7b2497e771952dd89600",
          "sha256": "0560ce09c436b964c56157ae903e96dea5b6fd4c4529a0ba615e1dee24a57d65",
          "sha1": "b3ee9e013391a07dda90303b562e03eafa83b7ca",
          "md5": "c6383f3df71700c07523bae7377727e1"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.2.jar",
          "size": 7714,
          "sha512": "4627658c56e80b582b90e199f02f23a9585e943cd9b82c0f3d9739555af3ce7d6985c852e86ce7880f19c2586b942af5da184ace1b9a7b2497e771952dd89600",
          "sha256": "0560ce09c436b964c56157ae903e96dea5b6fd4c4529a0ba615e1dee24a57d65",
          "sha1": "b3ee9e013391a07dda90303b562e03eafa83b7ca",
          "md5": "c6383f3df71700c07523bae7377727e1"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.2-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.2-sources.jar",
          "size": 6261,
          "sha512": "acab1a5585774dcc6114a3e7624d264b5e20df807c55b3869ecc76f67a43f6ab5d19bc17e83cc96f55579f229fd5a2ddf80342a2dc82154111ea68fd9b7b44f7",
          "sha256": "0f762f9892cc7ad3a3a1d4c31314166525331fcaeb50f1968087a129d0e6a174",
          "sha1": "ecd4af683230009fe0ad122a5c56627035f67443",
          "md5": "541e57909d71525bc0bbe6a70f176987"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.2-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.2-javadoc.jar",
          "size": 100575,
          "sha512": "241bced7a65c95008560c155ad456b057c86383847ed41f6184ba2f76afa6a36c4d5d47cd76a30c6c40f71d0c1be21955b80c1f2443fac1bca203e9769242fa5",
          "sha256": "415785c2cd2f8bad23c973ee1ad17797653b649179b4f800b3028c7b99f61f68",
          "sha1": "fd34cd2150890c56326061cc7962d85e73e4aa8b",
          "md5": "4332cf005706553a881745434d8cf966"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-common-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    }
  ]
}
