{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2.jar",
          "size": 17871,
          "sha512": "add510fa48ef819fd69f5c3e5891ce5a8bbd55b7127d2a172aae25a44a45d46eeab078afa1e6a520588c2d579955cd0d78f974032a605b80dc84f3da04e059f7",
          "sha256": "20597f079a977844beb62adaf4f09cb5c2d948fa010865ba3c1f08a78fd4193d",
          "sha1": "da0b30acaed6cf9152947fbaae2750afd67ac155",
          "md5": "6ece8c7a36ac234122edfad189ad1cbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2.jar",
          "size": 17871,
          "sha512": "add510fa48ef819fd69f5c3e5891ce5a8bbd55b7127d2a172aae25a44a45d46eeab078afa1e6a520588c2d579955cd0d78f974032a605b80dc84f3da04e059f7",
          "sha256": "20597f079a977844beb62adaf4f09cb5c2d948fa010865ba3c1f08a78fd4193d",
          "sha1": "da0b30acaed6cf9152947fbaae2750afd67ac155",
          "md5": "6ece8c7a36ac234122edfad189ad1cbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-sources.jar",
          "size": 12023,
          "sha512": "f25a04dacd14db196e54a9d0c0c8dde623d462e7cf282329a82840915668be5e15df913d2385f7a7e0f32be5c587c498da163bd5426866c431fef67b7c3da2fe",
          "sha256": "8f20eab83293aa135e491030495436d47b3b9e376a3a5fb3853fe1757b260212",
          "sha1": "a0b90186d43d81b99a612c830311fc6cd354eeef",
          "md5": "f614e3e70b185459c0cef1ef51138af3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-javadoc.jar",
          "size": 123576,
          "sha512": "365451d947d46b9de552e2ae6e094f46240746ea0bc3d7885615dc500511194237bf57666ea7e2f5df14fe33fe5fe87ceb5c9a94efa1c6601b12a211148d91f9",
          "sha256": "3fe02535c6e8924cd49699fae3c01cdb95a23230deb1aa0736c4eccbd5bc4460",
          "sha1": "63540fd31b75045742ae9eca2ffcc10ac72809e4",
          "md5": "e5895aee010e24ae51c0aabe41126723"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha2-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
