{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.1.jar",
          "size": 24385,
          "sha512": "ee5653cd730164fedd02f976bb0b904dd74247d5f43e4a5bc775a3ea6b78b007d58568310d15a2e45a169e0850aad9e716d91df12006719dd742335fb1c3252c",
          "sha256": "cb57627014ea65661f86902f442a49a97530a90c695a884dd4f49c757b539a7a",
          "sha1": "ccbb20507cf9ac3a808a9e0f6b887d35cd232f6b",
          "md5": "71389730a39385d2737b6e2c086e8a39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.1.jar",
          "size": 24385,
          "sha512": "ee5653cd730164fedd02f976bb0b904dd74247d5f43e4a5bc775a3ea6b78b007d58568310d15a2e45a169e0850aad9e716d91df12006719dd742335fb1c3252c",
          "sha256": "cb57627014ea65661f86902f442a49a97530a90c695a884dd4f49c757b539a7a",
          "sha1": "ccbb20507cf9ac3a808a9e0f6b887d35cd232f6b",
          "md5": "71389730a39385d2737b6e2c086e8a39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.1-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.1-sources.jar",
          "size": 18115,
          "sha512": "5356c4575b0f911e538f04e35ef270c926a0d1432bbb92f2ccceccfd44f870c8b01775b7610621b1c4a06f53fb7d3b2db8c6270341bb1a512840c8952577c6fe",
          "sha256": "866d7379893d3cb3ab045e40e16bb60608e6c0e447348663aba2fb2c87a4e611",
          "sha1": "a2cc205aec5b71076979c1c1e9eca1d738f88ff1",
          "md5": "53b9440d7d4782c3f40ef17ee711f917"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.1-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.1-javadoc.jar",
          "size": 159451,
          "sha512": "456121f5f77056f71bc934ec5667edfd3db8c8100fba1a6af472223406a38a0c1e5886e3f6592a1d00cc6e6c33f8c68640f7708eca3fcc18a27490a648ff201c",
          "sha256": "d65a7995b5368af61569f79ee6b6a9063bd33ed1f35292bcc3753e3dd7baa8a5",
          "sha1": "7f051dd7315613540f1ef40bf3b288fe5ccc3390",
          "md5": "86661780e37c249c3314670638696698"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.1-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.1-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
