{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7.jar",
          "size": 19347,
          "sha512": "28ebb69ae9b4058402dab1cc8969c85a01bba8e98bfa2edc522c7d9c02625798e3ff3f3e831650f6d4dc6773e0231f95b52a44485fc7711d0ed4e474c24fbbe8",
          "sha256": "3a50256673bca01cc3a7dafe48e546e3882b8b8d31a31906f0125994f371ed7b",
          "sha1": "e52ae32309de6201a3cb3288810b3de708476d34",
          "md5": "cc80ad811dcfad85e04411b0b49c6292"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7.jar",
          "size": 19347,
          "sha512": "28ebb69ae9b4058402dab1cc8969c85a01bba8e98bfa2edc522c7d9c02625798e3ff3f3e831650f6d4dc6773e0231f95b52a44485fc7711d0ed4e474c24fbbe8",
          "sha256": "3a50256673bca01cc3a7dafe48e546e3882b8b8d31a31906f0125994f371ed7b",
          "sha1": "e52ae32309de6201a3cb3288810b3de708476d34",
          "md5": "cc80ad811dcfad85e04411b0b49c6292"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-sources.jar",
          "size": 11875,
          "sha512": "e98fa58f4e2a27af3752b824e7617081c743f95700cf0a8fd7616805bec5eedc6b3c269ecfe5c65449cc2e20e9e5fa64a8e1261bdcd65ad2198f5e16b9ca6e93",
          "sha256": "5f33999623fd32d7d564361f7612b57683827d015d8e6528c1064f82731429ed",
          "sha1": "27123a20c1d3c2eb6e23132a52a3632e79021c10",
          "md5": "9cc559af206bd2bc29b125c10db24dd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-javadoc.jar",
          "size": 131206,
          "sha512": "98e382a6067b9b1192dc5e685ce210d5e1408deac5f7b6c1316955003072f885b396edeb6fcba70f3f0548f5a4360e24706c8af78bfb39bb0165879c377b885e",
          "sha256": "c21ed03ec8c5a4d138d060a19b44a1d388b44366d8c01572ff65de14b08e0306",
          "sha1": "7f4cb2803dfdbd4a1d71852aaef56e14bc9e9fc4",
          "md5": "4884ec914356059683193e5d7236b3a5"
        }
      ]
    }
  ]
}
