{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.3-alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2.jar",
          "size": 11390,
          "sha512": "b1f7ffca3c87eb9bb28464a7383b7548c3d433237f51726f165752bdaa306582df3ecdc9ea9dc56eadb97e0ddd2f9f8827cb2e11964e69e371b6650c56ab8133",
          "sha256": "7829cd34f9f91f2b1da7329c94a6f5524cc972c91c237fe7f4ef5777bdd6edef",
          "sha1": "6d52a001516cd3fdfff4c3f6b937d24b5f9d141c",
          "md5": "571b8ac1a47a6085610c9ddfbab288bf"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21+neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2.jar",
          "size": 11390,
          "sha512": "b1f7ffca3c87eb9bb28464a7383b7548c3d433237f51726f165752bdaa306582df3ecdc9ea9dc56eadb97e0ddd2f9f8827cb2e11964e69e371b6650c56ab8133",
          "sha256": "7829cd34f9f91f2b1da7329c94a6f5524cc972c91c237fe7f4ef5777bdd6edef",
          "sha1": "6d52a001516cd3fdfff4c3f6b937d24b5f9d141c",
          "md5": "571b8ac1a47a6085610c9ddfbab288bf"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2-sources.jar",
          "size": 9367,
          "sha512": "8c145e2b86424b0f6a4926a3f50a26391ab815ad92804b3d2fabe531a8dd807503932a15f2933e84e75e47f03c2cd5ed1aa15af41af87a61af675dead5b37feb",
          "sha256": "0a5140ca91d1a835d3dde8078fed0db93d72164a4bd78c21cd4ea2f9bd614c6b",
          "sha1": "5308bbd121997aa1429ece76f8f9fa576141a61a",
          "md5": "879663ffab1e5ed8d89dc9d14f2d3001"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha2-javadoc.jar",
          "size": 108253,
          "sha512": "2a81f485b3d8bde33e4350bdecec464b25d058d36c4eacc2c9189a75965774b1c77365c8811eb9e71efcdac3c041dcbc0e4b3d2fdbc552e7cbe620cc7d70e0ab",
          "sha256": "5970c8fc02763fdb4b4088e231423d57cbbc2395d2a656c691043f58225de1cd",
          "sha1": "b936654a9726ac805f4a0c0d4998b245fdab946a",
          "md5": "6926afb222fad6054a7287bd00a21c52"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha2"
        }
      ]
    }
  ]
}
