{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.0.jar",
          "size": 23482,
          "sha512": "77cd1ccd7c77e6115061b3b9fd5ccdf562d76f06406a48e166e2e62ca5318ea412d622522a325fe521addb54157bb390f56c36d902ca8ddbca39f72f0f3b7b22",
          "sha256": "78307a6e71e18ab2008b2768b93ca0e8495a802b77e27f67041487c10f800ca7",
          "sha1": "870810598009328b28fe1fb00ed33e07d44c0d63",
          "md5": "126734e3582e7fcbaeca7efebe8c9e7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.0.jar",
          "size": 23482,
          "sha512": "77cd1ccd7c77e6115061b3b9fd5ccdf562d76f06406a48e166e2e62ca5318ea412d622522a325fe521addb54157bb390f56c36d902ca8ddbca39f72f0f3b7b22",
          "sha256": "78307a6e71e18ab2008b2768b93ca0e8495a802b77e27f67041487c10f800ca7",
          "sha1": "870810598009328b28fe1fb00ed33e07d44c0d63",
          "md5": "126734e3582e7fcbaeca7efebe8c9e7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.0-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.0-sources.jar",
          "size": 17460,
          "sha512": "28ec69cf7c063c0a2f2100eb1d026203e94dc247a4c2de095827279b1c9ed2c281008486645c7c76947685d1fd7d2192d71f13a9a364befde575c860d5ce8c4b",
          "sha256": "e0a519738eb636d785b2600fc306eb7e7d397d1a35f6c61ba8e7d38b78a53006",
          "sha1": "d990df7fd00ead35a63725965a5a22fa464156f8",
          "md5": "16b227943cc1b6f4eb34878b57396804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.0-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.0-javadoc.jar",
          "size": 153386,
          "sha512": "300293c4664d45405326e5ad2cc7b59b67994a64dffbac0eb2e1cb7af0e8ee4ca41ce8c1b587422794c58abc8ea743df500cd505f0ae576196d0c3e959ab2c14",
          "sha256": "2c25a1149f31750c66fbadef5fde1e8ae9dab1a484a39c6980551235fa8bdf43",
          "sha1": "c9248b1d900aaf7acd098e038bcc4ec46006bbce",
          "md5": "68a3dcb4c4f4a94fadb91b8f6ba214a3"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.0-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.0-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
