{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7.jar",
          "size": 19941,
          "sha512": "b67616d630a4265583c501cacf3cc868ed5a3c5514d5f31292e105ed02460a63898c2a18c75860023a94353f9f190123878ddc4b76c8f6969c8370f708168916",
          "sha256": "78aa17b2e33803fcd9162ee2a3f57a21c46254322b4130683d787b6ca02bfcb4",
          "sha1": "e50181e24eff4b64fdd80c296479596ada12ccf6",
          "md5": "f51c0d27a31fee1e5dab0f384eba5454"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7.jar",
          "size": 19941,
          "sha512": "b67616d630a4265583c501cacf3cc868ed5a3c5514d5f31292e105ed02460a63898c2a18c75860023a94353f9f190123878ddc4b76c8f6969c8370f708168916",
          "sha256": "78aa17b2e33803fcd9162ee2a3f57a21c46254322b4130683d787b6ca02bfcb4",
          "sha1": "e50181e24eff4b64fdd80c296479596ada12ccf6",
          "md5": "f51c0d27a31fee1e5dab0f384eba5454"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-sources.jar",
          "size": 12166,
          "sha512": "aafff6ad795f98b96dab6afb6801ed9f84a6a8fbab8bb1ca77c6f1fda180d51f1cbb405d792b18b1f8e5187b5252340e178441e9d13ae012a966080e6b825853",
          "sha256": "821f08706d1e1978bef7528d6f93b2dd70656e1f21aa9a4fe97ed9c92184a326",
          "sha1": "9743e531f5a821cda2207b7f933fd22f099095c0",
          "md5": "d2dbd2298857e17cf68630512a6e1a07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-javadoc.jar",
          "size": 130932,
          "sha512": "64c90d06520339fa2a9af200a43bc6332ec56822ffb6338804ceaef71972cf51c41490afe6b1d480bdb771126665f4e871d094ac9dfcf8a0d827dd18f244b475",
          "sha256": "75896f2e20a9e66b83c05d7d3ebb5b9717f94164f7299841ec7302d54da01a24",
          "sha1": "e58d948602e85e61e9289cebcec1153cece4dbb8",
          "md5": "c2ca9b4e37e506b867e6b0f8b32242ac"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
