{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.9.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.9.jar",
          "size": 14526,
          "sha512": "f84e334aac32bb6bc08f1b94cc7fd5d75a427c4214f099a4e42a062bd1a794795e303763fc8eeb9d1d7c61eb119269888cbc707fc489135ad71e81a400737d4a",
          "sha256": "4b22c774685984d9a293e57d5a88cf67582fce394014d9627c00c068881c3ad1",
          "sha1": "7dea6d3a18e1858f7e79d5fc54beeab49e5a1a9e",
          "md5": "c6839f3a50046cbb5e616fb92248fa6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.9.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.9.jar",
          "size": 14526,
          "sha512": "f84e334aac32bb6bc08f1b94cc7fd5d75a427c4214f099a4e42a062bd1a794795e303763fc8eeb9d1d7c61eb119269888cbc707fc489135ad71e81a400737d4a",
          "sha256": "4b22c774685984d9a293e57d5a88cf67582fce394014d9627c00c068881c3ad1",
          "sha1": "7dea6d3a18e1858f7e79d5fc54beeab49e5a1a9e",
          "md5": "c6839f3a50046cbb5e616fb92248fa6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.9-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.9-sources.jar",
          "size": 11557,
          "sha512": "f0afb1644d0b66d3f969160094143be05634cb62499ceda61f1e3fdbcfe5f1150513db59ffa6728da9fa83779baeb772a4005ca7266f4d954dbe6410c67d7609",
          "sha256": "00fad2dbfbd4c5fbc88a432339dac027218684d26cc48a65bc002061297e1942",
          "sha1": "644ecaae6db82adc1310367ea2595be331db14dc",
          "md5": "2031fb8fe2399db2fe64cc44f907b9e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.9-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.9-javadoc.jar",
          "size": 134437,
          "sha512": "bed70d00710f22c122dd2ff11e022aeb2d6dc20ebc1215addacfb2f683ddaabdea17dd727904c425b76359acb6751853a1f4cb058b591eab210a76956be14fca",
          "sha256": "63138c20e82ed4db3373195edbb87ac7729e4eb6c45d2ea963dbbc125be79b9f",
          "sha1": "ed954c444434ef2564f4ed11e946cf90f37324e1",
          "md5": "3f2d07ab44af9754f31fa8178806621b"
        }
      ]
    }
  ]
}
