{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.6-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1.jar",
          "size": 17489,
          "sha512": "7dccfb275a275e516593fb85e2776e7f3bbb9cab3416c85169e4dc1f4c741ff1953a94c59940a444c2996d82f0a28bb9475ea60d7a3edcb90cfa0f989a05d42c",
          "sha256": "79eef1aa6985e8c1bea6df3a7f0a8d7df82ab1f983ccbfb716e5723a70ecd4c9",
          "sha1": "36ba4440924b1cc7f87029d7e68660657f743d33",
          "md5": "ff3866deacf018368c21b64fc41b237c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1.jar",
          "size": 17489,
          "sha512": "7dccfb275a275e516593fb85e2776e7f3bbb9cab3416c85169e4dc1f4c741ff1953a94c59940a444c2996d82f0a28bb9475ea60d7a3edcb90cfa0f989a05d42c",
          "sha256": "79eef1aa6985e8c1bea6df3a7f0a8d7df82ab1f983ccbfb716e5723a70ecd4c9",
          "sha1": "36ba4440924b1cc7f87029d7e68660657f743d33",
          "md5": "ff3866deacf018368c21b64fc41b237c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1-sources.jar",
          "size": 11752,
          "sha512": "ed90f0def5533fd50276e9fe824c700168802abb10398db8295d2d943220bb19a5595e21d99f38a1984aa6b76aea34154e3c46b4639810a20958b9d842c06202",
          "sha256": "e4cc268bc5139d219ae83292413a044022b5f017a57956402b783153471fbc3b",
          "sha1": "34f7b2440b83d9f2f5c2a2eb171c3ed9afbaf826",
          "md5": "d80fe0117ae3638333cccb65ffe3004d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "size": 123847,
          "sha512": "17c807ba9d7ccffc2183bd77a8337347c1ccb731b0c8220bf19389839bcaf7502078260b75f4c1337973c9f965fb951bb93a9fbd6eddd900d49666413c21b043",
          "sha256": "54f05a0bc1fba5aa55c48ea47d7a32773c5d65c95b8212a529126533e947dda8",
          "sha1": "895af917f0cd3dba0eb97f59575715437f269aeb",
          "md5": "e55a712360ffff78f550db41f0949cb6"
        }
      ]
    }
  ]
}
