{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3.jar",
          "size": 18578,
          "sha512": "ae8843248bf44e279f908202306f2c7dd30d0aa6ba47e7a403d4db854739fdd9925747f13a14f1f504bbcf99b6a086c47c482b090787d12e26075f14978b6666",
          "sha256": "5d1684b4ba5845efb764872aef9e7187209f7241d610046fd76ec85c0b5d7321",
          "sha1": "9c19f4a9d202ed5a5129bf4434d07d7afc34b596",
          "md5": "41c23c4339b0e048ff445cc2d4cd2c8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3.jar",
          "size": 18578,
          "sha512": "ae8843248bf44e279f908202306f2c7dd30d0aa6ba47e7a403d4db854739fdd9925747f13a14f1f504bbcf99b6a086c47c482b090787d12e26075f14978b6666",
          "sha256": "5d1684b4ba5845efb764872aef9e7187209f7241d610046fd76ec85c0b5d7321",
          "sha1": "9c19f4a9d202ed5a5129bf4434d07d7afc34b596",
          "md5": "41c23c4339b0e048ff445cc2d4cd2c8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-sources.jar",
          "size": 12967,
          "sha512": "658f625d16b7e47b1b5d633fc8b40582e7ac05600279268f436391be391f38e9a3d52a976ee0081873ac32a85c6da66610137d1d07039eadd50aa59d5ce828e6",
          "sha256": "e9b0ebb32bd0ff42c68640a0498e2e0b6aaf41e57b9a936ce5739213a9dcfafa",
          "sha1": "3fcd1dafd67d0b9f616daf26be397d5d1fe8e159",
          "md5": "88b15b82d42beace689b0ef5aff9bb0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-javadoc.jar",
          "size": 123227,
          "sha512": "c1e7e6a1f63e1b9fbdabd8da047a7b72d3f936f3ac3577ead9b412d65efbf1ff2a814bf222ae94a3f312e2490420778a311cc157bca8478e3ac13b74aade1e21",
          "sha256": "46d236e54e875542c84dd3f7a076b30811a5df8169b63435a7f9b7f518f892a1",
          "sha1": "1b900dee2175891d19599ed09be5e92e1c49a9ab",
          "md5": "1f3225c42fe6231db96b28929edf80d6"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha3-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
