{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2.jar",
          "size": 18603,
          "sha512": "b6f3763d9792f225f8c15ffd642f81bafe4afe3a262e82b06fa083df48d2496bb5ab6a3128e3ceb6bda259acc26c6e212dd82d9739e77139ead975f7f64050bf",
          "sha256": "262430afa82641d405982eaaafd35fc82297164caf2ccfcbd2cd83be2e7fe857",
          "sha1": "2f44492f55547533f0207efe2c948ed33ee3f322",
          "md5": "380502c5638ded2ad3504b757574cf8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2.jar",
          "size": 18603,
          "sha512": "b6f3763d9792f225f8c15ffd642f81bafe4afe3a262e82b06fa083df48d2496bb5ab6a3128e3ceb6bda259acc26c6e212dd82d9739e77139ead975f7f64050bf",
          "sha256": "262430afa82641d405982eaaafd35fc82297164caf2ccfcbd2cd83be2e7fe857",
          "sha1": "2f44492f55547533f0207efe2c948ed33ee3f322",
          "md5": "380502c5638ded2ad3504b757574cf8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-sources.jar",
          "size": 12807,
          "sha512": "454fc7633f3ad056b5a02e9d02de10e8f2bc32e28293f7231f2bd8d380d6fac97a7de07857b9835a45f9b4585d8fa1c3657fbdebb95bb9a58d178d01b6be7a6c",
          "sha256": "17296dc30c34730272b22bbce65ba801c0ae631a0c88fa7321f29f0d5029c485",
          "sha1": "18bdfb67c5ccf268c3d9fd13abd172a3a1a42b56",
          "md5": "3b068fca621875bc38136f76a09f7b9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-javadoc.jar",
          "size": 124175,
          "sha512": "d6e4d4cae6341be3f72fe57a824f1646b23cce3a3e3dc1640ccafa188a099ab82147f6b7de85d2d02433a45b332f79c0d8398d46b344389b07bb695fd14b7f21",
          "sha256": "297adea30e619e3b2d8001c8ded329594b95f41942a291c02cb372eb617d1625",
          "sha1": "fb90b4131467d4b13af92c72af5528ed9dec47dc",
          "md5": "3ba9aba83adaa46bc24626430ac3631d"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta2-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
