{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htravelersbackpackplus",
    "module": "gk1htravelersbackpackplus-neoforge-1.21.1",
    "version": "21.1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-neoforge-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2.jar",
          "url": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2.jar",
          "size": 14324,
          "sha512": "7817573a5397d6169a4a5c0c044ba486b9e133b6cbde001e0e67e7d56601ab225b3e2ecf8d08828b5fdbeb0952be00b7500f1a403087f3e7952c7c79177bb92f",
          "sha256": "e9694dd714c2424796faabbe4a8c449e2e4c6dd010fcd775cb2b186b0de59bde",
          "sha1": "5ed40fbf1d1adcbe4cc0f564588d31abd9f887ae",
          "md5": "891cc074ebd1d6a5e965e5315efc709e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "maven.modrinth",
          "module": "travelersbackpack",
          "version": {
            "requires": "1.21.1-10.1.29-neoforge"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-neoforge-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2.jar",
          "url": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2.jar",
          "size": 14324,
          "sha512": "7817573a5397d6169a4a5c0c044ba486b9e133b6cbde001e0e67e7d56601ab225b3e2ecf8d08828b5fdbeb0952be00b7500f1a403087f3e7952c7c79177bb92f",
          "sha256": "e9694dd714c2424796faabbe4a8c449e2e4c6dd010fcd775cb2b186b0de59bde",
          "sha1": "5ed40fbf1d1adcbe4cc0f564588d31abd9f887ae",
          "md5": "891cc074ebd1d6a5e965e5315efc709e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2-sources.jar",
          "url": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2-sources.jar",
          "size": 11854,
          "sha512": "eff46a157a8deb9417e5df9a97a0a3c7716fb119c84e1b8f6f2e959c193a156792e6f229a86d1e626b46e7819e4fd2bb9a7ce1a6a606323757685698f403fa2b",
          "sha256": "72fd6ffe8ee92469f39f97d2546d7262581d08f1c0aa4b6fbb01967a1df51efa",
          "sha1": "cf84afa57c3307cf1a44d96915d5a66bf13d029c",
          "md5": "7f8d600e4a74bdaf956afb4c8f398dac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2-javadoc.jar",
          "url": "gk1htravelersbackpackplus-neoforge-1.21.1-21.1.1.2-javadoc.jar",
          "size": 116197,
          "sha512": "f677b7e01fb3727d361eadeffd2062e388186771ac9aeda13d3f4d39f5deee172c314e4ee242d66e5b136aea57d91ec21d7bf4a3c8eb45cdceabb4b5d56f4551",
          "sha256": "c11a5b77c77a43b2ec9ed606dfbdd648ceebd9c53bfc3fd0226e0737eaac3b03",
          "sha1": "69946c80cf69347cc467c646339204a6fb0199e8",
          "md5": "c972d6cd7425b7549a3debba919b50bc"
        }
      ]
    }
  ]
}
