{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.3-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3.jar",
          "size": 11542,
          "sha512": "cc1ee8a677ca3c68629d88e386389ac31d12cbbcea53c3d9e216e736365d16f913d87aeff2fc07c5230fda3fc2974d8d01a0cdf1e28403faaf33c15e646e6c2f",
          "sha256": "0d66f95377ebacbd32e92e6eaf3f3b0968f05c158896fd4ae3f30721a71f8cfa",
          "sha1": "4ee2b63d9616d59639f141cee7c2eb43932f733c",
          "md5": "59817e9996cb80efa5c31302de848b0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3.jar",
          "size": 11542,
          "sha512": "cc1ee8a677ca3c68629d88e386389ac31d12cbbcea53c3d9e216e736365d16f913d87aeff2fc07c5230fda3fc2974d8d01a0cdf1e28403faaf33c15e646e6c2f",
          "sha256": "0d66f95377ebacbd32e92e6eaf3f3b0968f05c158896fd4ae3f30721a71f8cfa",
          "sha1": "4ee2b63d9616d59639f141cee7c2eb43932f733c",
          "md5": "59817e9996cb80efa5c31302de848b0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3-sources.jar",
          "size": 9440,
          "sha512": "7aa1ae60fdd332e9273480eacf785fb243574d03713baf955b6c05948020f79bf5f9813caebc15fd233c77a6b1909cfeccafa5d0b7d743772b06672dc124c60a",
          "sha256": "7a7c460a71ce6a8d9064a645344f906c785afb9606f3004f259ef9ad677ad765",
          "sha1": "4f21d2b9c9ed4db7495682588f1670024ece840e",
          "md5": "a82bceb0999982db47463f607909fb67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "size": 108734,
          "sha512": "f99c57ed22bd7d97ddf6e69abc907d1939773df817a029eda77f39cbda0417249c767bc0809d12c4e002fa03b958a0122f6a6963ec8109849b5af27e381ee854",
          "sha256": "77b43a44ac5165c84f329734d62e7e0f32ca391c1df208b53eea28b52962563e",
          "sha1": "aa3c604fe8a9a2a4bc3c14335c5bbfeb49c510ff",
          "md5": "284037c212ab8daa18bd92e9a9640985"
        }
      ]
    }
  ]
}
