{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.7-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2.jar",
          "size": 18990,
          "sha512": "71e731635efa22c0a5a9747de5e69918b74ce5146af8cd69279720e561c95786ccba538672192b38240577844117f56348aae70f302cb94566e11f1d36a5dca2",
          "sha256": "2d65336b75ba763cdf511f0f3134ef76a7b7ffc79ac13e295176ee28ba81c7b8",
          "sha1": "66c457fc7377ae7a1c6113e42efab5d967210c82",
          "md5": "3c4524952e2d5e81bcf12c9f657b78bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2.jar",
          "size": 18990,
          "sha512": "71e731635efa22c0a5a9747de5e69918b74ce5146af8cd69279720e561c95786ccba538672192b38240577844117f56348aae70f302cb94566e11f1d36a5dca2",
          "sha256": "2d65336b75ba763cdf511f0f3134ef76a7b7ffc79ac13e295176ee28ba81c7b8",
          "sha1": "66c457fc7377ae7a1c6113e42efab5d967210c82",
          "md5": "3c4524952e2d5e81bcf12c9f657b78bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2-sources.jar",
          "size": 11739,
          "sha512": "177aac498e1bf877d26ea5f2f489a5d67f6392598c0532b345f599d34f621e0cb4411bfaa592d4f1f87f7a49cd31418aedd4df8c910739d4398537e22c7c48ee",
          "sha256": "51e0d401e3f6ffcd6756db1ec057a6c733b69087529f7a7f6601f0e9afddb170",
          "sha1": "8fc1556405c4ef31b6a22b3e04a696326de1df65",
          "md5": "6d48ee799bf50201b948cd0a979229e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "size": 131053,
          "sha512": "9522ab91b053afd55407d2a403df17b3c7e61d8523606153e7ab109f23056fe8408293e47865bf70fadf4c9d9ccf9e6d44b58df22c2f6444ba8c0337b5b66563",
          "sha256": "9998c0af9637210932552d049a44d42b10361f6c2a3a15981a672076a0700406",
          "sha1": "6cbacc650a2d597bd57b44f0324eb41f0fe03406",
          "md5": "f80c110a6fa34fe6def373cd75a6e031"
        }
      ]
    }
  ]
}
