{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.7-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta3.jar",
          "size": 13080,
          "sha512": "66d44ae57ef733f0c7f65154dcc4676f067c292e6943e9d70ec09e016773bddef5c81495be19edec2e86f5151fa1ed5df3d590c03110fd58d8e12054949d65f3",
          "sha256": "f6b1e52e599596758f54f9e46e14c89729f1f839855596a625257292884ac36f",
          "sha1": "b8b7f8edab648af6d4f6ee0f20de50b16368841a",
          "md5": "aaf39c30b4c126cd6cd9d4577d63b4e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta3.jar",
          "size": 13080,
          "sha512": "66d44ae57ef733f0c7f65154dcc4676f067c292e6943e9d70ec09e016773bddef5c81495be19edec2e86f5151fa1ed5df3d590c03110fd58d8e12054949d65f3",
          "sha256": "f6b1e52e599596758f54f9e46e14c89729f1f839855596a625257292884ac36f",
          "sha1": "b8b7f8edab648af6d4f6ee0f20de50b16368841a",
          "md5": "aaf39c30b4c126cd6cd9d4577d63b4e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta3-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta3-sources.jar",
          "size": 8034,
          "sha512": "008226eb739c74567a9c9ac8cfaec3b76829646fb59566f31a6b21c913d0d070c1a2c110bb553a5527160dbdb3b7de228169db9ec2f27325d906b8937fe25fb7",
          "sha256": "05844c922c10cc4a6860b2f51f8fb0cdf6fa5a7e6dc61c502e1018d2763ff2da",
          "sha1": "ef40f8a0e54652b07701e6b7ff6a8b32678e1677",
          "md5": "32138dae793f1e0f36f811d2c3dd9b3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta3-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta3-javadoc.jar",
          "size": 122322,
          "sha512": "c24ccc224024710caa96affe56285d3bbc4687925899e468d6269e44bd8df9528803f6f3765de1c68c9802309c84e83f8993e876deb883dc4586cadc234bfe74",
          "sha256": "57e935f7a791ce78875d30a9b28a8f617d6476d2a0092e3de2c0f7301945c9e1",
          "sha1": "36d7123a2c2b274f0bdad15ee8d59718b9124c41",
          "md5": "406a013c9cee97c34e14821b4d0856b5"
        }
      ]
    }
  ]
}
