{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3.jar",
          "size": 18224,
          "sha512": "2bcd3ec599bbc098c8854233845b36530cffcae6b87d26fa6f9b9fe174d4665722a6e2624291b801132ebe10d676ece08f0c1c91bc729ba4c21fc9d045595c4b",
          "sha256": "3875cc352e72f5be1dd089adf1395a2bc0eb217f3e13fc48aaa0733b2e449010",
          "sha1": "dff104fe4cb6be871a46c78169c57ccc1d3e1afd",
          "md5": "4f020d333efe866727780ceda4bd3453"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3.jar",
          "size": 18224,
          "sha512": "2bcd3ec599bbc098c8854233845b36530cffcae6b87d26fa6f9b9fe174d4665722a6e2624291b801132ebe10d676ece08f0c1c91bc729ba4c21fc9d045595c4b",
          "sha256": "3875cc352e72f5be1dd089adf1395a2bc0eb217f3e13fc48aaa0733b2e449010",
          "sha1": "dff104fe4cb6be871a46c78169c57ccc1d3e1afd",
          "md5": "4f020d333efe866727780ceda4bd3453"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-sources.jar",
          "size": 12598,
          "sha512": "574a1235d2465631e0eb3861166a0c45b404144725665b92490863493c66edde4b429efd932b3442fe0ee05a5c3f77e54481f7c12a5ce1c3634061561b38c275",
          "sha256": "9ee0b70b175e002fd9d9db1cabe0b29367717d36748231ba930e6b926d5303b7",
          "sha1": "9b5939b454e6a911aaae0218e483c7eed5e437b9",
          "md5": "feaa8566795d9452c589246067caa73e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-javadoc.jar",
          "size": 123184,
          "sha512": "6b68fd678239e2fe6ccee8225afb5d8623ac33fdb1af5bd9d4fe72fd5bf8a315102cfb8ef700fdec1a3b7afddd9132032bd272546e517aa4554529937f02359d",
          "sha256": "6e9b2ff8cc20bcc511c5df66536bc015e0be8c63d52084bf208f65777ad23ea5",
          "sha1": "5604c2bac1537b560a4676f96d0ead962937abb5",
          "md5": "6f143ec79f1bd2410d5a1eed0eb72c7f"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta3-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
