{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.6-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1.jar",
          "size": 17747,
          "sha512": "094f4589b0bb9d553a16555aa57b68dc417d510c8775e4bfd02956cf0f7399f5bf8d865d21c6f318a6853b581cc1053ac6773c578dcf66c1ec1f34e1a16ab47a",
          "sha256": "97a8ef6de437fa3dc7f0c2c9f8f40f6c980820891d5a7259ff505c2a6b797c2d",
          "sha1": "570f0eb93b4eb3079f3f4ef6ecd96e2b1b1cc952",
          "md5": "dc46b94841dabe6c1b4facb1547b8d88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1.jar",
          "size": 17747,
          "sha512": "094f4589b0bb9d553a16555aa57b68dc417d510c8775e4bfd02956cf0f7399f5bf8d865d21c6f318a6853b581cc1053ac6773c578dcf66c1ec1f34e1a16ab47a",
          "sha256": "97a8ef6de437fa3dc7f0c2c9f8f40f6c980820891d5a7259ff505c2a6b797c2d",
          "sha1": "570f0eb93b4eb3079f3f4ef6ecd96e2b1b1cc952",
          "md5": "dc46b94841dabe6c1b4facb1547b8d88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1-sources.jar",
          "size": 12361,
          "sha512": "b3c038e53bcaf107a949a0e6bd88b37db69f65713eb81597e17f52efa404cb483fc674e845b5ee6b4e4d5bbd3c28cf6e07fde50214e943a52433f3d04d23e22b",
          "sha256": "3829d74dcf3134ffe5abe782faf3eba93073e85507a1e4f9035062c3114ec338",
          "sha1": "f679d40ee3a279850c725d38841060002e8eac3e",
          "md5": "b9bdf8f6bbf4fe08e159855f2e0cebf5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-beta1-javadoc.jar",
          "size": 123459,
          "sha512": "e896b67ad4ea198db8fdeda3e68c42b47bcb708c0247eda56f12addaf940363a2872beea4feba4d72092bcba341f75c00965a96b2c3bf785991e3a8c849925aa",
          "sha256": "8eaa8e689ae056c1be12621aae0d46cebfa60266a138d5db1cf462d0533da228",
          "sha1": "6772bb0af42930cc051f01a0fdf91cff0d40e885",
          "md5": "d5e3bb302923806a6076d5d5c670e6e4"
        }
      ]
    }
  ]
}
