{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 14299,
          "sha512": "d0a46faa4633e4caa5b9a48c655d1bc2890871c3ef32f5aa4c1ca49fb374938d6eb70227b5b3998426b70e1bac61bdcbba522ae2e6c926373ab2fe488cfe34e1",
          "sha256": "450b32f45f28c1e596cdb2d6fc1ef8eb80c3146eccc6f2e30ac470313b37772c",
          "sha1": "cb9655001bbdc06df081ad81e92885704a384e2e",
          "md5": "ae9a5bcf3c823528613b99301997d815"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 14299,
          "sha512": "d0a46faa4633e4caa5b9a48c655d1bc2890871c3ef32f5aa4c1ca49fb374938d6eb70227b5b3998426b70e1bac61bdcbba522ae2e6c926373ab2fe488cfe34e1",
          "sha256": "450b32f45f28c1e596cdb2d6fc1ef8eb80c3146eccc6f2e30ac470313b37772c",
          "sha1": "cb9655001bbdc06df081ad81e92885704a384e2e",
          "md5": "ae9a5bcf3c823528613b99301997d815"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "size": 9084,
          "sha512": "5acb5d279d6b326db1f05f0f5c13d39ab2340ddf0ee70b46cfdc5fa4ab788a4258fad61e45f5a0cbaf7908c12f39dea5c068c416db3615426d1278104df65103",
          "sha256": "ba0d5d34f4515c46140b1c1b927d4631ef354262d820b0f33089ff867246143f",
          "sha1": "bfcbe03252ebee51e0db526bfbf6447708fbf0d2",
          "md5": "724c6814596f0085f40fcb0aaa849187"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "size": 129371,
          "sha512": "1057710331b057748b3d0f522be483209a49fd21ae3b7f0fb5cb1e3128278da43d096cbd639728fe7b93cf2ef4e6b411d0cf2bbdcaef8d3ba1eee2fa9194d529",
          "sha256": "b7c2af334fada7d76fcd64c097c6163d296924fa95e36375e54bae4b336b49cb",
          "sha1": "617b0528fb5d46b9e2e5870831188d8580252e7c",
          "md5": "864f27ce96001f09d8058eb3f093cef8"
        }
      ]
    }
  ]
}
