{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6.jar",
          "size": 12647,
          "sha512": "e481e064076d8674401964dc65d7ec13e2c2c089cca70a59373505e9f6b04086c70709a1377ef9c5dc33ccad5ddf618856ad6b4d99a022c7b59b54a25082ea1d",
          "sha256": "b73516eea5998f4965b29cba8a96efba7feff052e01720bead24351958db630a",
          "sha1": "fff8e60fb7abb5c2c9438cecc3dd049b1181ba6e",
          "md5": "8f7790eb0c5d1ba1c8be05ea7e4f9cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6.jar",
          "size": 12647,
          "sha512": "e481e064076d8674401964dc65d7ec13e2c2c089cca70a59373505e9f6b04086c70709a1377ef9c5dc33ccad5ddf618856ad6b4d99a022c7b59b54a25082ea1d",
          "sha256": "b73516eea5998f4965b29cba8a96efba7feff052e01720bead24351958db630a",
          "sha1": "fff8e60fb7abb5c2c9438cecc3dd049b1181ba6e",
          "md5": "8f7790eb0c5d1ba1c8be05ea7e4f9cef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-sources.jar",
          "size": 8739,
          "sha512": "d2fdcf50d141ffa7ec1943d02477ce3f5a20644e607cbd4faebb22cc011dd18e4416b9f2a97df863d030a351a13aff26e05128e0c01cd570db8bd97dc1cedc4e",
          "sha256": "e006b2b8565a56bd5f2551111c39268fb74cd700ee42090c6e629db2ff06cd0d",
          "sha1": "07e6597243ced78b6fbd56743e997c8b8591ecd3",
          "md5": "6734b19b7721a3c6b4127b959bc9a250"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-javadoc.jar",
          "size": 114210,
          "sha512": "e7863e1d73e73720ab0a01a705eb167fefcffdd8a84c2db9f68fc0c70f43c79dd73e92c836f46640a9448b86a5ed7b2dd4d5f5a3b0ebd99c47d5af07d8def50d",
          "sha256": "059453ebc777ec49cccef9dba1b6693470a0434f910b736873b10e9d7eb4b8bf",
          "sha1": "b84f2f46e5740fb4e4bf84b99fb61e5c9df6d95d",
          "md5": "be3df390828b8807f107f27320da7ec5"
        }
      ]
    }
  ]
}
