{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-common-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 19464,
          "sha512": "f27d4a541c686af8b91f46d7f5f58bc493829b4563293e7188deb1e81f50796494c6da5d0c7f9b1b9d666d66edb05c0fa7b4ea7fd500ccc3d2e6d3124fdc8064",
          "sha256": "142c5d48a3a3f7721ee151f6f1d5f3f92d8297188090303f57747012785bdeb6",
          "sha1": "5ec623f9162eb360b786348d12611be19dd8ceb4",
          "md5": "ab95760c9f7835a35a840599b7632beb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 19464,
          "sha512": "f27d4a541c686af8b91f46d7f5f58bc493829b4563293e7188deb1e81f50796494c6da5d0c7f9b1b9d666d66edb05c0fa7b4ea7fd500ccc3d2e6d3124fdc8064",
          "sha256": "142c5d48a3a3f7721ee151f6f1d5f3f92d8297188090303f57747012785bdeb6",
          "sha1": "5ec623f9162eb360b786348d12611be19dd8ceb4",
          "md5": "ab95760c9f7835a35a840599b7632beb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 17359,
          "sha512": "dacc5308ab9821260b0da1705ec12c242a2adc7c332282d29d75c37296df14fb0f5bd7bf42c55e8197237ff387910969904e32a91b22cc697aaa6349f4c8517b",
          "sha256": "59e6225e5a7545b87a02404f3130b982192f3738775676a218034161bf22e68d",
          "sha1": "ed1cc1fb16edc3ed6bd3076ebfd327f1101e9b66",
          "md5": "88f02fc29df5f94fe8d359015642a450"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 113342,
          "sha512": "2f589ccd70e23ccaf770f8d2e8003d6dbcda051353850c1bb007c417dba2edb0d4804e4e0253d4d4bf18e2dfb3aa59d4417daae098afaf9fe74d30a91f1b8342",
          "sha256": "45577ad5db6f2a33ca5a27d63da5d90e4417f82205845c0601f9699888e3b319",
          "sha1": "424b21c02bcb0c648d65f3e6ce178fc0f925193f",
          "md5": "f63d09f013d42eade8136c9fb1e73c25"
        }
      ]
    }
  ]
}
