{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-common-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 12963,
          "sha512": "a82665b30baf6012f47d947c37aa1faac09ccf1912c56064e44c6e52d6acab181e35187acb9d4d17f77518464af1e7edc3f122329ecaac7721609cda5d40b198",
          "sha256": "df970fa23b57b3e37f73a3e22882e17b3dfe015027421f01c40ecbccf75870e6",
          "sha1": "d4769b7ca17aa1e9265d4bc7582e73252b0c6df1",
          "md5": "3b4f04871c01492c97f3ee357e4d4b40"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-common-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 12963,
          "sha512": "a82665b30baf6012f47d947c37aa1faac09ccf1912c56064e44c6e52d6acab181e35187acb9d4d17f77518464af1e7edc3f122329ecaac7721609cda5d40b198",
          "sha256": "df970fa23b57b3e37f73a3e22882e17b3dfe015027421f01c40ecbccf75870e6",
          "sha1": "d4769b7ca17aa1e9265d4bc7582e73252b0c6df1",
          "md5": "3b4f04871c01492c97f3ee357e4d4b40"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-common-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 10916,
          "sha512": "755772461e1d15601e5a4bc1719b626641c6f29c9399912f7b6003d5411fd553397af2fe114c29e334482fc3b7083b15d95e0d9fa6b818e356927c5553313617",
          "sha256": "437aff4000a261e169a7eac0c6e67078d36edc2b98f7c4db68de6b5a1eb5b2a5",
          "sha1": "53b86b810e91b3b29a87ed0d53133179077780ab",
          "md5": "ced56c6bea6cdf2685ad6f56bc6d2230"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-common-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 113167,
          "sha512": "12ed0c7ecf975e191122cf60067a815eb91a711acc181727594bfe787ccdc953fa531fbe4b754beac6c680727f082e9502e919c9eb64aa1ed9b92047f594820e",
          "sha256": "ae4a829bb8413162b14cd23cda30946716a9091a46df5da00354cd4057c4241d",
          "sha1": "8848898aa0c8a80a1c315594734df909f8610a17",
          "md5": "06a449908d76b792eeb8548e299c879a"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-common-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    }
  ]
}
