{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-common-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 19782,
          "sha512": "8d7f400e7e42c467af8c32fb78dd5eaa17e818f5696e615d02149c21637216803055174702b60045e9aed1af3b995a08a8e693e3efa3d6f70c9329ac9f91544e",
          "sha256": "164354e725d872899841c6bf6067436308955a9fa001ae442e627ea4b4f42765",
          "sha1": "4ae8faf38d4b66332627ab739a0dc9c1e9f59223",
          "md5": "5ea4f0d1b2e0789370bfff8f6e694431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 19782,
          "sha512": "8d7f400e7e42c467af8c32fb78dd5eaa17e818f5696e615d02149c21637216803055174702b60045e9aed1af3b995a08a8e693e3efa3d6f70c9329ac9f91544e",
          "sha256": "164354e725d872899841c6bf6067436308955a9fa001ae442e627ea4b4f42765",
          "sha1": "4ae8faf38d4b66332627ab739a0dc9c1e9f59223",
          "md5": "5ea4f0d1b2e0789370bfff8f6e694431"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 17673,
          "sha512": "ff6e7abbda3832e726d7d00b20f7ad5cd9dd23591930510e6dd229c3be5c9531fd9f77852934b1827d0dfa23cfa02926a86ad489346a3b7d56be16c2dbc1ded3",
          "sha256": "77968ce9f5b5a2374641d75ebebffc7faeed164376b5fd8faa0283e203b8fd53",
          "sha1": "2d9725104a30546d40b3b5af28b728e96716f6ce",
          "md5": "c2f2edd9b62f66ee75255966493ed674"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-common-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 113516,
          "sha512": "c6ee4f16ca254c360e574b02067fbab388b8e1301cb5b43f53c1ac81390b242e77e8a745d31886fea7c847b402c81f9f0f995bf113ca65f53fab95f6673af7f9",
          "sha256": "2bb6eb7b407155f92d15d746cea875cbbdc6087017f383b2972aaa342afb6a20",
          "sha1": "0e326cf8392543f5780e2b5a59590ddc31a2a157",
          "md5": "a6e2f9395fc446c4c45e2b118a28f091"
        }
      ]
    }
  ]
}
