{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.4-beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta4.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta4.jar",
          "size": 11552,
          "sha512": "26c7583c755829728326c269d259dd226c21e03b8efddf45277b0242e59e69f092ec4f90598a18d016500125fcd7864fcbca55570d52817c7375f9c987bf1b3a",
          "sha256": "9bcc1e70adc223dde2ed92cf08f6aa7e2f3b3fc3d7e157096db6d8b5b4d4f92f",
          "sha1": "068eee27f000eab3c98d578a06cb9e908f877968",
          "md5": "d96fc8308c62aa51006b4dc1c106405c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta4.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta4.jar",
          "size": 11552,
          "sha512": "26c7583c755829728326c269d259dd226c21e03b8efddf45277b0242e59e69f092ec4f90598a18d016500125fcd7864fcbca55570d52817c7375f9c987bf1b3a",
          "sha256": "9bcc1e70adc223dde2ed92cf08f6aa7e2f3b3fc3d7e157096db6d8b5b4d4f92f",
          "sha1": "068eee27f000eab3c98d578a06cb9e908f877968",
          "md5": "d96fc8308c62aa51006b4dc1c106405c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta4-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta4-sources.jar",
          "size": 7762,
          "sha512": "277398be01750b13b64715d371393d90cf7e7ad67b67550002bab70c6797588e52c58620dc614573dd2a29e553996a05fd7bb7fefbb35f79266e4dd8b50c8411",
          "sha256": "24d9ee06845c661dc098d4f151a335f43a8ef9256ed1e18aa6605c605f404335",
          "sha1": "b84360f19495c4ff56c307a1202b43bc926df1a9",
          "md5": "1895023bb0252c1a056aef388adadcd4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta4-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta4-javadoc.jar",
          "size": 114323,
          "sha512": "908bbdddf65e6e83ac7208eef2cfaa019fab43e7b058bf9c0196785406f7262a0ca4e9249eb944968f2e01728b0cd3515f407e3c5a08583b879b6b9819225da6",
          "sha256": "1d7a3da2f96e453bbe998b70a59ead85b6ccf581a708700ff2ce18e2913c183e",
          "sha1": "7e532b9d24cfaf44361d1f3ba1dd65abe41604aa",
          "md5": "0b74f52c37ed8897cf2dda19b636bd89"
        }
      ]
    }
  ]
}
