{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.3-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha3.jar",
          "size": 7720,
          "sha512": "cad87fa2ad4dc7c99a0c1996682885b110fde8a1ae0ed78e535854898a82e1a18143c89b9bfce8ae60c1b939abf89a179bae8b5585c816b6bdb845fdc422867d",
          "sha256": "279656ec5adab78c1e16c58735cb20c5fe96a636724e916588083c90a8564948",
          "sha1": "e211a3a7704360aa5e5d3e870343d9d91b7a4ee1",
          "md5": "a0495e0429ac77fc149ca0f0caf3a188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha3.jar",
          "size": 7720,
          "sha512": "cad87fa2ad4dc7c99a0c1996682885b110fde8a1ae0ed78e535854898a82e1a18143c89b9bfce8ae60c1b939abf89a179bae8b5585c816b6bdb845fdc422867d",
          "sha256": "279656ec5adab78c1e16c58735cb20c5fe96a636724e916588083c90a8564948",
          "sha1": "e211a3a7704360aa5e5d3e870343d9d91b7a4ee1",
          "md5": "a0495e0429ac77fc149ca0f0caf3a188"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha3-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha3-sources.jar",
          "size": 6261,
          "sha512": "acab1a5585774dcc6114a3e7624d264b5e20df807c55b3869ecc76f67a43f6ab5d19bc17e83cc96f55579f229fd5a2ddf80342a2dc82154111ea68fd9b7b44f7",
          "sha256": "0f762f9892cc7ad3a3a1d4c31314166525331fcaeb50f1968087a129d0e6a174",
          "sha1": "ecd4af683230009fe0ad122a5c56627035f67443",
          "md5": "541e57909d71525bc0bbe6a70f176987"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "size": 100692,
          "sha512": "43d47331f5f6603f8176aa96e98cac6e5f403af9e414089fdc94c0c64ec18244e8becdb27c024b6a4f377ae1582fa6a20f729d8817ce2cc88a09bfcf011e5afa",
          "sha256": "0432728d92dd4d84de536125c36f4bc97b99b2edff5b1ccc63ac55154e388d51",
          "sha1": "1fd1e42eb0edf6a8d18b60b6a30cc4169a9ffff7",
          "md5": "4e98496dece60a55a0bfafe01c8e3ea6"
        }
      ]
    }
  ]
}
