{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.6-beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta4.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta4.jar",
          "size": 12465,
          "sha512": "ab60a593e3dd93567a78d8d017675b904cbdec1901b855e8632a8332939a98e945cacf9794eeb5983db2730c235f3bb18446198388d66798c9aff3289af0cdfe",
          "sha256": "355e3f38eba6230a1d74dc91276c4df77eedd24e4dbd109fddf5be2b30882874",
          "sha1": "4bb78e7df25998216794bd3bb3c6f0800a5b5e0c",
          "md5": "088bfa6914e91e75990d82c41ee95b40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta4.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta4.jar",
          "size": 12465,
          "sha512": "ab60a593e3dd93567a78d8d017675b904cbdec1901b855e8632a8332939a98e945cacf9794eeb5983db2730c235f3bb18446198388d66798c9aff3289af0cdfe",
          "sha256": "355e3f38eba6230a1d74dc91276c4df77eedd24e4dbd109fddf5be2b30882874",
          "sha1": "4bb78e7df25998216794bd3bb3c6f0800a5b5e0c",
          "md5": "088bfa6914e91e75990d82c41ee95b40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta4-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta4-sources.jar",
          "size": 8740,
          "sha512": "2b96aea402a79c62114ad8aa428856056827c9d79770051cab334c6792399649c6cda7a89df6d44372ee1a3207b381d6665615724fc737639c94680d2f201441",
          "sha256": "87a7fb9e54d12ab9e901d75fa863a706f095d7305d59bee31ffe7851d280a52d",
          "sha1": "0cdf5b84dca546ec28488d93a77563b3370c6d61",
          "md5": "45ffeee5971b15858eb5540f393fc8fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta4-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta4-javadoc.jar",
          "size": 114324,
          "sha512": "831715fe2bc0d8467b2ecab8a16850cf11ee7066f428906af981a50cca13844e5a29d6e95b689c29dcfd6679c48db30a27fba67d4d9f2e18b0056977f147c5f1",
          "sha256": "62856f68b6b5c981d645c6c3101608060c66c5e5d1c57713143114a5c1d30827",
          "sha1": "b19d296e9fe999bc4a5330de1ae67433f18153d8",
          "md5": "84f2a4787a3eb81ad5bab7921c1e78e1"
        }
      ]
    }
  ]
}
