{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21384,
          "sha512": "c8fb02b248337788d24154872c315f685f50642bf1243a7d79860fc53d1435e0e68f4e5910562711762cb4d7a89096c9d6fab989995e7214889297ae08cb6717",
          "sha256": "5a3357c56b0daf57466ff42e0c69e99b0baa0682fcef3aff9a197c40fb962fb8",
          "sha1": "b5fc1053a64ae93b139469d221cb9c31db71ed34",
          "md5": "6cf98167f77098dee5e2834fac580bdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21384,
          "sha512": "c8fb02b248337788d24154872c315f685f50642bf1243a7d79860fc53d1435e0e68f4e5910562711762cb4d7a89096c9d6fab989995e7214889297ae08cb6717",
          "sha256": "5a3357c56b0daf57466ff42e0c69e99b0baa0682fcef3aff9a197c40fb962fb8",
          "sha1": "b5fc1053a64ae93b139469d221cb9c31db71ed34",
          "md5": "6cf98167f77098dee5e2834fac580bdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "size": 13609,
          "sha512": "3a6fcb20f8ac7ea506507d21658db481c4237d85bc1fbbe2e6eace5be22671f909b1e1b1c9cfb4363389e5245700bc92b008b7636d4c275f0edf27fb876663aa",
          "sha256": "4f811e23188ad31baafbd6fb48bb365af1b2541b1920eee76efb7f7bfb49ebb9",
          "sha1": "6143fe4a0027a13600272b280a68d5c9e6a3224f",
          "md5": "804640445c822d2f9f964711643d39fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "size": 140959,
          "sha512": "2893e340925323a1f0abe3b62817741c35d92ab047705fc1cad4de67d3ebe0e6e0e9518dcab6f5870283ed05ed812c8ff6b0b7b64dc61cfbb54cbd71abefc198",
          "sha256": "77bf76369a15e6bdbb9a1454624ae4603379a18cb6202945928379bc0a347e82",
          "sha1": "df907e9dc689ba957beefcad8a95981c85fdb0d4",
          "md5": "915c38959b3850f05a2ef082554d25fe"
        }
      ]
    }
  ]
}
