{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21483,
          "sha512": "4a26e67f78dadc64656ba323b98d00cdc61795e7c12afdb441cfaac86c826040c607de3754836fb253e5416fcd56f7d63f642f7bccebb22f258663a386d2c5cb",
          "sha256": "49996c03da360cab612483c978be8debfaf0c10cda4ff76951796583c981a186",
          "sha1": "3faafbd8edcb3b642a35722a8911bf3225d91f89",
          "md5": "ee86f2b3b6640505188ef7afd72e80a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21483,
          "sha512": "4a26e67f78dadc64656ba323b98d00cdc61795e7c12afdb441cfaac86c826040c607de3754836fb253e5416fcd56f7d63f642f7bccebb22f258663a386d2c5cb",
          "sha256": "49996c03da360cab612483c978be8debfaf0c10cda4ff76951796583c981a186",
          "sha1": "3faafbd8edcb3b642a35722a8911bf3225d91f89",
          "md5": "ee86f2b3b6640505188ef7afd72e80a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "size": 13647,
          "sha512": "7057ef75f294049e351762988fd1ad853f6461d13210613f9d7ae81a9238f48842cf6f1debcb7c234cba4b15e42db063d2591c13d1075fae84d0b5382ca70e28",
          "sha256": "8b7e180e8c667a1a90d356d5e2e8e4f84f57b163d94f656cbb2b135fa5e9cb50",
          "sha1": "cef9d2ba78d33029cf38da3e9456c8bf25066387",
          "md5": "584fe6add29c23c85581e254949dff45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "size": 141149,
          "sha512": "e6cc723a86b46cc5651e8257664223ce673e1b07c959d2169e13516ae0fdf00614e43b22d10f248f2015cfe0c657b9838aa1d34b612636281d569b05400852c9",
          "sha256": "e00480d116b441271971cbb0f615ae005a4c2acff5a654f24295457abfc565e4",
          "sha1": "4185209fc9de293e1fae652fe37328589133c5f0",
          "md5": "7f02e5c400ab7492103d5c57b85bdb30"
        }
      ]
    }
  ]
}
