{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21473,
          "sha512": "95b55c8d29aa8e766272e58c79dd7d44527b39ce612c9c8ead2b408ef2efdec559afdafce107da2f5714318f4cf3c174932baf7306009a4b22675861e274a570",
          "sha256": "3116ded9ba713b34b11291728ac0a828f75dcaa48caed78323d5598a243d6332",
          "sha1": "aec8d5d777b587ef018d0dbcfc2e7d212e7e0d8c",
          "md5": "b7a1dda8ae677a6ea0e66797e762e91b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 21473,
          "sha512": "95b55c8d29aa8e766272e58c79dd7d44527b39ce612c9c8ead2b408ef2efdec559afdafce107da2f5714318f4cf3c174932baf7306009a4b22675861e274a570",
          "sha256": "3116ded9ba713b34b11291728ac0a828f75dcaa48caed78323d5598a243d6332",
          "sha1": "aec8d5d777b587ef018d0dbcfc2e7d212e7e0d8c",
          "md5": "b7a1dda8ae677a6ea0e66797e762e91b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "size": 13647,
          "sha512": "9cdb658239b22d4bf57404624027a6b8c6fc29012171271fe30c6a835b42db0eaf671bd024f9cc3f18c5d69486f06a10e22f6e28c60da95800c387987b3d00b7",
          "sha256": "35ab18ad37467e8dee65c901d711262f058ceabdd4b3dd33d3175fb03af3ffd2",
          "sha1": "c004cf4d1e80d9773cab453a88b4fc1a3da12128",
          "md5": "e368ffbb8e0b2b522f56730bd6f9e2e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "size": 141149,
          "sha512": "e6cc723a86b46cc5651e8257664223ce673e1b07c959d2169e13516ae0fdf00614e43b22d10f248f2015cfe0c657b9838aa1d34b612636281d569b05400852c9",
          "sha256": "e00480d116b441271971cbb0f615ae005a4c2acff5a654f24295457abfc565e4",
          "sha1": "4185209fc9de293e1fae652fe37328589133c5f0",
          "md5": "7f02e5c400ab7492103d5c57b85bdb30"
        }
      ]
    }
  ]
}
