{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hrecipes",
    "module": "gk1hrecipes-fabric-1.21.1",
    "version": "21.1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "url": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "size": 58599,
          "sha512": "53b584cdc5056696d28eb540d3c6f3e017e5164f420d87d91833db52bc520b911aadccb4d2f808cbe9bbdcf6dd884c83261106ca78cb84780880d3943fbcef97",
          "sha256": "2fdd3635cbf5734741aa6f12a163cdfbd346f9a4c12f319e0fb7e1c03ced35f9",
          "sha1": "8e6055b0dc6bcb90ccda212c9c38b14cd2a84025",
          "md5": "03106aebd93314578b3515ab468304b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.0-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "metal-bundles",
          "version": {
            "requires": "v21.1.1-1.21.1-Fabric"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "21.1.39"
          }
        },
        {
          "group": "fuzs.iteminteractions",
          "module": "iteminteractions-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "advanced-netherite",
          "version": {
            "requires": "fabric-2.3.1-mc1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "spiky-spikes",
          "version": {
            "requires": "v21.1.2-1.21.1-Fabric"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "url": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "size": 58599,
          "sha512": "53b584cdc5056696d28eb540d3c6f3e017e5164f420d87d91833db52bc520b911aadccb4d2f808cbe9bbdcf6dd884c83261106ca78cb84780880d3943fbcef97",
          "sha256": "2fdd3635cbf5734741aa6f12a163cdfbd346f9a4c12f319e0fb7e1c03ced35f9",
          "sha1": "8e6055b0dc6bcb90ccda212c9c38b14cd2a84025",
          "md5": "03106aebd93314578b3515ab468304b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT-sources.jar",
          "url": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT-sources.jar",
          "size": 56448,
          "sha512": "5b238d64ee336096a3c775a5a0a42b3c6e800fa9decb34e287ae85dcd42cefd0b19b86ed2b70726f86da14e4f138b761903f1dd151c98081fabd8052d7f3e579",
          "sha256": "cf3ef9487e611ae0498f6f7bfe5a537c8cd9e940372c5a23f15b07fa9409bc45",
          "sha1": "f22f73fd8dacf9263ad98fa1176d01b37d1f58a4",
          "md5": "6ea8e611c216e33724243a8d0657f752"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT-javadoc.jar",
          "url": "gk1hrecipes-fabric-1.21.1-21.1.2.0-SNAPSHOT-javadoc.jar",
          "size": 117908,
          "sha512": "1a5becee1955cb7d4a5b5dcba8a0d2feb61e8a91fe377e514c42315a4f78fd53b99d4be85cb004ff333eff3bb2d5bcb803ed93ae73c422dcfdf2f471b02b9f51",
          "sha256": "82e2625e78053badc9190985ce6bf1d337232cf9f47c363ac49ddb4d63a2df9a",
          "sha1": "8e26b197418dcc4906177b31bb4aa6e37cc28748",
          "md5": "af40aed50a76d9bd430328f11aa870a1"
        }
      ]
    }
  ]
}
