{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7.jar",
          "size": 13081,
          "sha512": "26446c2469353245ba24f31ce276a57aee428a4982f7aac91cc3c3b441d911162582576177eb17594b5fc08c2e5e08cdf453b4bd8833a01db12647578579b7e5",
          "sha256": "c23bbc4c354136daf1b3bc9e9f3f11bcfe348db3509a909c75fee84d8cb592ce",
          "sha1": "945455a3a8ca61109bfdfdd83caa5a1084208954",
          "md5": "6cea8aca96b6f709e430f709b446204e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7.jar",
          "size": 13081,
          "sha512": "26446c2469353245ba24f31ce276a57aee428a4982f7aac91cc3c3b441d911162582576177eb17594b5fc08c2e5e08cdf453b4bd8833a01db12647578579b7e5",
          "sha256": "c23bbc4c354136daf1b3bc9e9f3f11bcfe348db3509a909c75fee84d8cb592ce",
          "sha1": "945455a3a8ca61109bfdfdd83caa5a1084208954",
          "md5": "6cea8aca96b6f709e430f709b446204e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-sources.jar",
          "size": 8040,
          "sha512": "44ea8a95537240a43ad17716949b696d2edd1ad7222208ff34772f8ad8b88e95c6d8fc4e237f5f95a9ecf80a285fe61b103df9fd4a91bd0e31705f68dc4f6840",
          "sha256": "8b47c738f6e4ab4695abf99b79f0f8aba8f8b7a9c34f2da10405754dbe21c1cc",
          "sha1": "16809fabc04a90ba7097e8fff205d8abe5deb5d6",
          "md5": "d13f5bee8e9ad659937ffdf7514ee3c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-javadoc.jar",
          "size": 122252,
          "sha512": "c0804cf022b401611c53504973aca24c4fcb83f4912504269a2a761eea9b25efb261649cd473ba845fc5c8e4d572b4489eccab16deb517d3e09419ab53eab1ac",
          "sha256": "f235ea1ec5ac70ef8acd420a8d56b7fb5f47e29264cca8d6735416137d2758fe",
          "sha1": "be77b3026db98fe051dc133a50cc2a7ed94a1022",
          "md5": "ecdaa89c6d11bae65ddf9deefbd7bcb6"
        }
      ]
    }
  ]
}
