{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.6-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta3.jar",
          "size": 12115,
          "sha512": "1f2251dcd27da8bf66035e1de973d3fb17416ab622fc591dd44f7fbbc7e564e2034d4a80caec5db2eda7ddc9d97bcf9bf17811e7eafc0121714343cc37d2e09c",
          "sha256": "7b52b7fa71dc1c26701711b683be04c62d25ca15fed6828845349d127a77b203",
          "sha1": "e5b6bc99bc951f2a184e593d982f02eb877bcbcf",
          "md5": "97ddd5375089f15071f7cdc361e23f3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta3.jar",
          "size": 12115,
          "sha512": "1f2251dcd27da8bf66035e1de973d3fb17416ab622fc591dd44f7fbbc7e564e2034d4a80caec5db2eda7ddc9d97bcf9bf17811e7eafc0121714343cc37d2e09c",
          "sha256": "7b52b7fa71dc1c26701711b683be04c62d25ca15fed6828845349d127a77b203",
          "sha1": "e5b6bc99bc951f2a184e593d982f02eb877bcbcf",
          "md5": "97ddd5375089f15071f7cdc361e23f3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta3-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta3-sources.jar",
          "size": 8390,
          "sha512": "a37494f50d60e113cd391ee944a10a26e0eb18a3f7675582970a0c8cc76718115370f8285632edc07087d1f67c5cdcf5f1f994c10131391bf89a5616d13a57b2",
          "sha256": "b5e42ab1cb90ea458849d0d6430a7591288c609cf520163b856d18f950d28586",
          "sha1": "83f7e4f8d6d41596f1dd204395a10e51a88dae1a",
          "md5": "e460e5e99c069378ce88a14012431a80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.6-beta3-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.6-beta3-javadoc.jar",
          "size": 114321,
          "sha512": "ff00867570179b910e8fe8a63a3ec07e23bfac1d9655c9b8dee69e0d2761d492a045c8081cadbfdf29c94006aeb3f55750b9b2d1527548689fde2d6a33f4730d",
          "sha256": "7faaa14af81a68b8117ddcc2e710623b595c8ea3e6e17ab6d9f4b8d2f4d11151",
          "sha1": "c7d9c565bc6762b3f5f152a98de401be561fb599",
          "md5": "fb9050384fc3b634ac4a6db7c942f25a"
        }
      ]
    }
  ]
}
