{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.7-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2.jar",
          "size": 19792,
          "sha512": "37ccc6ef6a89894b97d9d24a095cdf28cdf12741d11043615746c53adc2a75a36c7f843094123cea3447d29195c77844b332ab1220ffeef8b68df43535039662",
          "sha256": "18eb2eba69d0a1bd07802747a430d7776501f484dad035510b60f53fda93a697",
          "sha1": "786c9f7b7f3e1b600aa7b5703d6a17d1eecd8d17",
          "md5": "fbb0de89b43cb534abe0b3b33932b915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2.jar",
          "size": 19792,
          "sha512": "37ccc6ef6a89894b97d9d24a095cdf28cdf12741d11043615746c53adc2a75a36c7f843094123cea3447d29195c77844b332ab1220ffeef8b68df43535039662",
          "sha256": "18eb2eba69d0a1bd07802747a430d7776501f484dad035510b60f53fda93a697",
          "sha1": "786c9f7b7f3e1b600aa7b5703d6a17d1eecd8d17",
          "md5": "fbb0de89b43cb534abe0b3b33932b915"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-sources.jar",
          "size": 12091,
          "sha512": "9c8b2ba095463a4eaf8b6be5d04e94f1afcd193ad4736d3e6194dc9500ec67440994c5f5b800d61e5a5c417610913faf8ef72ccac4b1f2ddb457e0c99c018718",
          "sha256": "8ce6eab87f737b10f4668fe0203a18540ab3eb2f5d068ba257c4317d0dd1bb5f",
          "sha1": "ea445cc9b8a54a4ecb158f50acb0eb8acda1157f",
          "md5": "85bf24d68727c4b9329a06b8c7a407ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "size": 130763,
          "sha512": "da4b4d0ca7d291d0bd77d3904d388a70a3bd5f000e4f3b655e8b3890ee32ddcde568a42f5226281cf37d8241be2ac80cba9972f0ea74968ea101a2d6a7a3eaa8",
          "sha256": "06de9844258710ecd2da3c8be05c77474823ec1918413bc16f1f2c921770cdbb",
          "sha1": "f5be7611c536a104ae9bc9915d041df3c674fa5f",
          "md5": "cc87ea27ad8cfd7526d09e844d27c37b"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta2-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
