{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hrecipes",
    "module": "gk1hrecipes-common-1.21.1",
    "version": "21.1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-common-1.21.1",
          "version": {
            "requires": "21.1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "url": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "size": 53179,
          "sha512": "480ea09bb8feac60c4dc6c5d2ecc676fc13a8772dad7647ed9919a101d46d97089bfa806d7f1c8ad82e7d1cf050e5959e4d83a222abb6bf808e27ccbb22776d1",
          "sha256": "54413787f2261d1cb74ba7c1e8f4a2dfca55ce85e951210cfb3c6e5791352584",
          "sha1": "02018dc1c40c949ede93492bee9ff6e1ba61f7ec",
          "md5": "c8d6a7a57d2d7b03b4f773e74f1d3c29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21+neoforge"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-common-1.21.1",
          "version": {
            "requires": "21.1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "url": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT.jar",
          "size": 53179,
          "sha512": "480ea09bb8feac60c4dc6c5d2ecc676fc13a8772dad7647ed9919a101d46d97089bfa806d7f1c8ad82e7d1cf050e5959e4d83a222abb6bf808e27ccbb22776d1",
          "sha256": "54413787f2261d1cb74ba7c1e8f4a2dfca55ce85e951210cfb3c6e5791352584",
          "sha1": "02018dc1c40c949ede93492bee9ff6e1ba61f7ec",
          "md5": "c8d6a7a57d2d7b03b4f773e74f1d3c29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT-sources.jar",
          "url": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT-sources.jar",
          "size": 51446,
          "sha512": "bffa2a6beeea61a03d092a5e3137721c3013d9dca520b22cd3a41cb0a6d687b85467161aafee0133dd6ad0796528355019d564f2a72ebf5ffeb2b916ac788f96",
          "sha256": "a7999681bc53aa6b72d41887cf849002e9060de4e97660224319e78a12bdc37a",
          "sha1": "46dc79fc7138c3f29d2b253ac8ad43dabc73aac4",
          "md5": "494caf038f25d0f314662986ebb15953"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT-javadoc.jar",
          "url": "gk1hrecipes-common-1.21.1-21.1.2.0-SNAPSHOT-javadoc.jar",
          "size": 109527,
          "sha512": "ced4b6b3105237d52165012f1d943f62b97d35f9113e9f1d1f8e42d113d89ad6f29703d3302d72bc1914f097ae22f727652a5ae7658fb0a2a3728405b7bfdd4e",
          "sha256": "5ed6fa74243f290b1dbbc65639a6e4458b5416c2b33efebead92eea790c4eb28",
          "sha1": "fa8ccd1ebf3df4158a711ffb866c403f37770c42",
          "md5": "ae5179400f7b621112f663cc0d0daa46"
        }
      ]
    }
  ]
}
