{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.3-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1.jar",
          "size": 11389,
          "sha512": "d7d2ce97e798ffbb8947f291825762caf8bc5d08d7dbdc053ca27f814852bcdb1d0e586958356cee2a19c9d5bf09cce645d877e1f9e9602a4aa99150604e479f",
          "sha256": "b2b5f2c258e860baa5bd5c011343decd0c7226538f70c974d68ec86d3aa8326e",
          "sha1": "59b7114220a4455fa0c11ad62f9926bd70ec2a57",
          "md5": "bd9b6cfbf370eac33fba52e87f74cf91"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21+neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1.jar",
          "size": 11389,
          "sha512": "d7d2ce97e798ffbb8947f291825762caf8bc5d08d7dbdc053ca27f814852bcdb1d0e586958356cee2a19c9d5bf09cce645d877e1f9e9602a4aa99150604e479f",
          "sha256": "b2b5f2c258e860baa5bd5c011343decd0c7226538f70c974d68ec86d3aa8326e",
          "sha1": "59b7114220a4455fa0c11ad62f9926bd70ec2a57",
          "md5": "bd9b6cfbf370eac33fba52e87f74cf91"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1-sources.jar",
          "size": 9367,
          "sha512": "8c145e2b86424b0f6a4926a3f50a26391ab815ad92804b3d2fabe531a8dd807503932a15f2933e84e75e47f03c2cd5ed1aa15af41af87a61af675dead5b37feb",
          "sha256": "0a5140ca91d1a835d3dde8078fed0db93d72164a4bd78c21cd4ea2f9bd614c6b",
          "sha1": "5308bbd121997aa1429ece76f8f9fa576141a61a",
          "md5": "879663ffab1e5ed8d89dc9d14f2d3001"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha1-javadoc.jar",
          "size": 108253,
          "sha512": "d05f12cbb71f1412c463ac523f68fbbe4ed760c2d323b1a8ee023059593739d7db821be07174e898d4dc8c915c88df60bf9a5b35561f44c407192e5847690233",
          "sha256": "6e857f6e4ad22659a51f85a3c5f83299d3f0cee2acbac37919533fd749041783",
          "sha1": "57ec1549a13bfb8d3b5777f381043b2f6f6269de",
          "md5": "6a435ceb487d36edabafc0772b5d8078"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.3-alpha1"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-neoforge-1.21.1",
          "version": "21.1.1.3-alpha1"
        }
      ]
    }
  ]
}
