{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-neoforge-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 38460,
          "sha512": "c92dcdffd6b098e1e99d7730fa5f58476e4214d8a251bfbe22fbb8c0d5570f442ffdbe98adfdbb770010483c0e51f88808a1cdf8ff616b40bf63fe3d5822ca32",
          "sha256": "c9fff916256e37351d5c439c88b358043202e648a9571d1a1bae712a53ba7591",
          "sha1": "4b81aef127d6262882a32141d29027dfabc2031c",
          "md5": "b6fe3a9aafd2c79ea98d7bd4d4c5065e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 38460,
          "sha512": "c92dcdffd6b098e1e99d7730fa5f58476e4214d8a251bfbe22fbb8c0d5570f442ffdbe98adfdbb770010483c0e51f88808a1cdf8ff616b40bf63fe3d5822ca32",
          "sha256": "c9fff916256e37351d5c439c88b358043202e648a9571d1a1bae712a53ba7591",
          "sha1": "4b81aef127d6262882a32141d29027dfabc2031c",
          "md5": "b6fe3a9aafd2c79ea98d7bd4d4c5065e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 29243,
          "sha512": "472a24565f25351198677bf7ed01e2f2654b8b80282052996fe70c087437dcc30005e89d54e893a21ab35f06e860eeb54bdf7ed925c1b447d86092fca8ce516b",
          "sha256": "a80de158e13db18834c3d5a88f2e939c56cb27d88805b41e9710a174fcf26f08",
          "sha1": "b89cc563a10f5f74d80dfd942b6d791e640d978d",
          "md5": "f17a37c74308c714c06f7e3eded1a6de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 175778,
          "sha512": "d6e3dcec8106fbb4df774cfd227ffa9b69adff3dccd7eedb7f12f0f5bcb119d10b95ecefa2115364958111a3587c1acc7ed524e54b12ab0024142b363b85864b",
          "sha256": "1704f40cf78bd89f48025d3333f27d37221e396a2bc2c471d6502aac15e6b0b1",
          "sha1": "3843a50686522128cc5c65e0bf5f0adb5ff76ff5",
          "md5": "58488cbe0326f5405f262464478be649"
        }
      ]
    }
  ]
}
