{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-neoforge-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 38435,
          "sha512": "28d462579a76bd11dc7b5c32abc7ac9095dd7306c6b2daed817ff5ba9a3fbc26dd2d97d7e22f958ede3204c57d20fbfdee768c8a9ccb67868f6d3cd618027b0b",
          "sha256": "3ff7c25ade5ea2d86b96def982e8b1c4c926591f88d539c7a19be5db425e8b33",
          "sha1": "7f702a2d874926b282a6f210495eb65399277580",
          "md5": "2e0c86b2104a76b62e1569a5a53daca2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 38435,
          "sha512": "28d462579a76bd11dc7b5c32abc7ac9095dd7306c6b2daed817ff5ba9a3fbc26dd2d97d7e22f958ede3204c57d20fbfdee768c8a9ccb67868f6d3cd618027b0b",
          "sha256": "3ff7c25ade5ea2d86b96def982e8b1c4c926591f88d539c7a19be5db425e8b33",
          "sha1": "7f702a2d874926b282a6f210495eb65399277580",
          "md5": "2e0c86b2104a76b62e1569a5a53daca2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 29224,
          "sha512": "db7fb87b8744aabfd55b11f390f59d2b135539bd753b9915a84f292461b8917a191e1f7d613bce9c3bb487dd3cbe226dfccb1ac03620cdb8f0b6b3c31832278d",
          "sha256": "e65935e70877bfa02069d7e7527892347e27666f11661dd6e80b102b185ea61e",
          "sha1": "3b0ef18c1843c661c66ac66d8c070e2276491a61",
          "md5": "53f89921b7038f26ae3e614495fc5420"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-neoforge-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 175778,
          "sha512": "d6e3dcec8106fbb4df774cfd227ffa9b69adff3dccd7eedb7f12f0f5bcb119d10b95ecefa2115364958111a3587c1acc7ed524e54b12ab0024142b363b85864b",
          "sha256": "1704f40cf78bd89f48025d3333f27d37221e396a2bc2c471d6502aac15e6b0b1",
          "sha1": "3843a50686522128cc5c65e0bf5f0adb5ff76ff5",
          "md5": "58488cbe0326f5405f262464478be649"
        }
      ]
    }
  ]
}
