{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.7-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3.jar",
          "size": 19345,
          "sha512": "6478f5668e6199aba08fccba416a1477a29713c46ea1d73bdf8315ac8e3526b797df9f8d145e4741786480d71ab08818cbb18dd1aab06595c7fe3d06c7d51f9c",
          "sha256": "320d056e328825daeb894ec30ac1f347368f5de5209f6c2f58e1f88b6fc27d38",
          "sha1": "0711cc94b3ca2bf841c1164ac72b9ea62d739c66",
          "md5": "514207b262be676941a51b32b34a6375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3.jar",
          "size": 19345,
          "sha512": "6478f5668e6199aba08fccba416a1477a29713c46ea1d73bdf8315ac8e3526b797df9f8d145e4741786480d71ab08818cbb18dd1aab06595c7fe3d06c7d51f9c",
          "sha256": "320d056e328825daeb894ec30ac1f347368f5de5209f6c2f58e1f88b6fc27d38",
          "sha1": "0711cc94b3ca2bf841c1164ac72b9ea62d739c66",
          "md5": "514207b262be676941a51b32b34a6375"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3-sources.jar",
          "size": 11872,
          "sha512": "9ef27ae08ae374522c5ffff5676dba37f8cbba277a65f51d789d49c903ff4efec7da88ca4fa99bf909df3c7b68a1e781b8a843fcba783a7931a79603ffef0cdf",
          "sha256": "d61abc1c69c20b82a368dd10710f85cfcb12a57852b03252ed69259ceb2b4683",
          "sha1": "d4172feec916987c35e110287592148a0991c90f",
          "md5": "558e7b81f441bdaaa3f855e59ec5db65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.7-beta3-javadoc.jar",
          "size": 131261,
          "sha512": "a6c19515f3268bcd70dc80381a6ae60614cb5b235f035fbfb89f56ecd20215ce3219ea65dba34d3a8674f5d0161fe77399186a2555f6b9f44b24cca637ce1217",
          "sha256": "a594617bbf4e03a3ea4e131c0a9c5d7179a912db16bc1a2b942c5fd3b39820a2",
          "sha1": "7471f680cfb3f0214711ca4c030c53e79f7ee412",
          "md5": "0da471cc6505f95b3855012317d2e6af"
        }
      ]
    }
  ]
}
