{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.6-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3.jar",
          "size": 18142,
          "sha512": "a8db65b3244c8e478de4d8c7527a75a3ca5c60fe8e8479efc9997e88e58eabbd651671c3393d69a562a7f296c5d6ef2d49c001d57122df5fd0e09bb31a7a306d",
          "sha256": "6475c4e3b85a1bd00b96fdfc25847a54598aa4e70f0409ceebf236a1ce7a1613",
          "sha1": "d5de0e3378b71a1b506564adba16ca5862ef0c14",
          "md5": "ca18845b0b2882431e2b244f8ac9867d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3.jar",
          "size": 18142,
          "sha512": "a8db65b3244c8e478de4d8c7527a75a3ca5c60fe8e8479efc9997e88e58eabbd651671c3393d69a562a7f296c5d6ef2d49c001d57122df5fd0e09bb31a7a306d",
          "sha256": "6475c4e3b85a1bd00b96fdfc25847a54598aa4e70f0409ceebf236a1ce7a1613",
          "sha1": "d5de0e3378b71a1b506564adba16ca5862ef0c14",
          "md5": "ca18845b0b2882431e2b244f8ac9867d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3-sources.jar",
          "size": 12779,
          "sha512": "9993890eca301b54e8d454121c945ecf8845a39c823fbf6b89a1772feaf58769938575f209d02fd0b81a79ea8eecbde3a008ee03821e88cfa62c74b24489ba50",
          "sha256": "50b9ff5687143a80065a05c21a94949e73e5dcd1c15e113d06d48b8ff924e1e2",
          "sha1": "b4f494ffca26a7083d50d09b963372fba9bb8699",
          "md5": "25c2f6067cdfcb11361b8e4860261e6e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.6-alpha3-javadoc.jar",
          "size": 123506,
          "sha512": "7ad81180b9d95b55b134afd024cb851c5aed9072a207835e4f76d3b934cd35808cca8208e3e86789a500788b57550e827ef12097a7d883b26e2383a4d693fba2",
          "sha256": "7971f646277878b6d1ec90abf501127e0d6ae3df49a0b17b0420e3173d2863ff",
          "sha1": "a80d3c1486bbdf365af0ed4280a933925f0102cf",
          "md5": "648b51ca735b9fa554ed46cf2dc92b64"
        }
      ]
    }
  ]
}
