{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24131,
          "sha512": "0e52eff33ee3b2812b8e5e6906edc1041adf2bab477d2d5dc7f92ccb1adb6f04f2ba94cf00a28eb177dd39af5bf6ac4b4da4c0aa86370b790123ec1ae3e4d97b",
          "sha256": "fd81fef3c3633678fc4fdde52c10c3a6cb02c93a87b4ae751e42410ada4957cd",
          "sha1": "47b52a0a756c369bc9fc3d8630a25c01e115d6bb",
          "md5": "26d02d57ac9672186dbc257e4f011f42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24131,
          "sha512": "0e52eff33ee3b2812b8e5e6906edc1041adf2bab477d2d5dc7f92ccb1adb6f04f2ba94cf00a28eb177dd39af5bf6ac4b4da4c0aa86370b790123ec1ae3e4d97b",
          "sha256": "fd81fef3c3633678fc4fdde52c10c3a6cb02c93a87b4ae751e42410ada4957cd",
          "sha1": "47b52a0a756c369bc9fc3d8630a25c01e115d6bb",
          "md5": "26d02d57ac9672186dbc257e4f011f42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18280,
          "sha512": "fb33efd1829dc2c168b578d9b47464269a03f1a98249a8e3601b5de266ac816a00c5313ea976bf71d371007218933590b2df751317f1d76586efca2f48962ce0",
          "sha256": "ca0863bfbdbed00ed9bd5e3662c19cb4b31dda8f8d84dd2cf31783ea2352e1b3",
          "sha1": "2affcf1383f4cfb7f8593d67cc7b6257d9957433",
          "md5": "259f65680a63dab75a74f3c4d612320a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160324,
          "sha512": "267f0080e9deef08d0537d9c8e479e9931fe54459ade7f1f292e6c7c1c958e2fe799f12cc4f130d70135144b33ad759fbe62b73a584bc82dd279e1b6a5bf2106",
          "sha256": "7fa6b9dfa2148e6e0c9b0b886ae9d7ab35731c7511a61eac12610572c3355586",
          "sha1": "1e190867aa25d06d9db4e3ea566761b9fa26cc0e",
          "md5": "c20066a993266120a864df21694f9920"
        }
      ]
    }
  ]
}
