{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24394,
          "sha512": "e88123f01c6eca01de4d12c1e0ea424dda7f69436989524cbf6ccefa2f3fc6f55adc8d0dd322746ccdf453ba250c1146c722ced49254dbfe8a3d16db19d3b1bf",
          "sha256": "0a91d546bf87ca1a923a5d74471f65f77db6c4d43fdd2a9faf898b7bbc640c47",
          "sha1": "baf29fd60671990a23858921b9dd662e9b867655",
          "md5": "74041daf4cff202409e137f14d4f16b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24394,
          "sha512": "e88123f01c6eca01de4d12c1e0ea424dda7f69436989524cbf6ccefa2f3fc6f55adc8d0dd322746ccdf453ba250c1146c722ced49254dbfe8a3d16db19d3b1bf",
          "sha256": "0a91d546bf87ca1a923a5d74471f65f77db6c4d43fdd2a9faf898b7bbc640c47",
          "sha1": "baf29fd60671990a23858921b9dd662e9b867655",
          "md5": "74041daf4cff202409e137f14d4f16b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18454,
          "sha512": "ab15170b30a4072009817403f84a289d19953531c6b9c9180e26b372b17e4ed02555bdfc7fbf978a342357a4dba4b17a117dbebc87a0b665d6fa4abfe5447899",
          "sha256": "ff8787b9be10e7ee3c0da32da9130ddf97db8e6ece9048d3220617d1f14d8fcc",
          "sha1": "114e0380a09580d9a32c549582ad54e452082035",
          "md5": "c13dfa6eaaedab2912135fd362099fa4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160925,
          "sha512": "437cff0ee2518d83a16c894e77885540ccd35d372b99a36a1a4a729ffdeed72a897019fab7ab5f5795806c9dfab2e6780e8e91dc77e0bc3a6888b03fc2aa645e",
          "sha256": "c242534778d058e2648e583d11cdcaac8175fc91365f98f2636c04a7aad257d8",
          "sha1": "72bce947f087dfa21bd7994ed80e368776ad73c8",
          "md5": "f0ec925e050faa0bb85ef911d2081fec"
        }
      ]
    }
  ]
}
