{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24435,
          "sha512": "7f342006ac43ea8f90fcb7074c5cbc3b215000d843c8399719947b95521140334d91a960deeb20857a594f10cb3439f08107f6d7352151556e6f254e5bf51386",
          "sha256": "870d471aae919b4dee88ac45f84c3168f557fadc3206c7652d88bf20dcef35aa",
          "sha1": "c5b5f73226725d1e1dcb6bd2cb244ab9d20c80d9",
          "md5": "a2c7f6047c11574d8662ca1008f5f876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24435,
          "sha512": "7f342006ac43ea8f90fcb7074c5cbc3b215000d843c8399719947b95521140334d91a960deeb20857a594f10cb3439f08107f6d7352151556e6f254e5bf51386",
          "sha256": "870d471aae919b4dee88ac45f84c3168f557fadc3206c7652d88bf20dcef35aa",
          "sha1": "c5b5f73226725d1e1dcb6bd2cb244ab9d20c80d9",
          "md5": "a2c7f6047c11574d8662ca1008f5f876"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18504,
          "sha512": "aa408d53bf4df3de958030424e8c689b38487a881267d91fe270a9125226462f5fb8717e56c74ae7458b8d44ac8716d72c1e785f85c73d49d1477ce4e2de1433",
          "sha256": "10bb7fa4d0b792d44b45ed928fbb0bed39ae5945387b955bcd1dbb96cdc51d97",
          "sha1": "a3dc43ca26c930d7d7115ea8d7ccbed16e12665c",
          "md5": "22ba38df074ac456c008c090a3c7683e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 161029,
          "sha512": "92a7da1a320c35320777fcaca60deb49b6f6ddd5064af7d67648dfc844f8c21ed3120ec99fcf71291b770cda2cc946b37782ae9f5dcc2aa421a61a57f5200308",
          "sha256": "1b45e87977ac489aa72f31f1a6bcac3816a3948d62f93d54c09cfd3463cce98c",
          "sha1": "71fa68385013fd1178638138c03824e960b45905",
          "md5": "4490feb0234b105093ee9895c252808b"
        }
      ]
    }
  ]
}
