{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.4-beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3.jar",
          "size": 17278,
          "sha512": "f9359cfdb0501aca3d58b0a678ab9a67bf2de2d7d6d554a2c63130e574cb36c8340aa678cfbe384d68eb9ec10f131eb31fb5c48eddd530a12a435d553f125c6d",
          "sha256": "7c724749f04b6f8694a43ef3dd95cebaf93109f9793b7056d8c6b32a3a96c143",
          "sha1": "e9b21baf51819cc11a14c4d234faee0faa028e93",
          "md5": "051023a4fb8174271fc218b804b7d666"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3.jar",
          "size": 17278,
          "sha512": "f9359cfdb0501aca3d58b0a678ab9a67bf2de2d7d6d554a2c63130e574cb36c8340aa678cfbe384d68eb9ec10f131eb31fb5c48eddd530a12a435d553f125c6d",
          "sha256": "7c724749f04b6f8694a43ef3dd95cebaf93109f9793b7056d8c6b32a3a96c143",
          "sha1": "e9b21baf51819cc11a14c4d234faee0faa028e93",
          "md5": "051023a4fb8174271fc218b804b7d666"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3-sources.jar",
          "size": 11889,
          "sha512": "88158b1fd05f31da8c3af426baa5485ce1329962052ac3569ebf57108eefbb16aac1386c2abc9fb6f083d77206ea021b1597617adb3c9a07f12c1a12f827c807",
          "sha256": "157233a91bd3c0b39c165dc4a603a62d4739f6c55e28f6e4193b86f6c2c6d56e",
          "sha1": "517f9debfe11c4615ede96bd14a7d0a00531240e",
          "md5": "920011de2689ffd281f430e99edc3ba7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta3-javadoc.jar",
          "size": 123365,
          "sha512": "0b0b8bc2369eb07b689b3518ddcb2f11d334d38fc5a769a4c8ec76246597ed1f6a4f1e65812c4e97b5f1b623a7d0242b44b415d071d195647c572a7bddeba1d0",
          "sha256": "cf989d30710a3f077987fae0d9361bc711fcf28d622268b8973df2e32ac412ee",
          "sha1": "72aa216267ba7b20f1da016d601517cab47ab420",
          "md5": "f5c69c78dfda59275c1d2376c45d17dd"
        }
      ]
    }
  ]
}
