{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1henchants",
    "module": "gk1henchants-fabric-1.21.1",
    "version": "21.1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1henchants-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1henchants-fabric-1.21.1-21.1.1.2.jar",
          "size": 51107,
          "sha512": "017a4871fbb4cbb1c3f0f63e3e6edab096ff914fe0fc20c751c6ba29f58da319761515add21f409da955258b135fd01410caa63bf15075a4f8eed1a91e5f07e4",
          "sha256": "1fcfbc680aa08a1f4148b01445153f6b954925a5630b044dcf36b5842d7911bf",
          "sha1": "1c7ce77176856d8754ae444e8a4376254027c2a4",
          "md5": "451e53be67d1e4d2b010a5759a8baf75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.4+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "universal-enchants",
          "version": {
            "requires": "v21.1.6-1.21.1-Fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "netherite-extras",
          "version": {
            "requires": "0.4.0+mc1.21"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "21.1.39"
          }
        },
        {
          "group": "io.wispforest",
          "module": "owo-lib",
          "version": {
            "requires": "0.12.15.4+1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emi-enchanting",
          "version": {
            "requires": "0.1.2+1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emi-loot",
          "version": {
            "requires": "0.7.7+1.21+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emi-ores",
          "version": {
            "requires": "1.2+1.21.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emi-professions-(emip)",
          "version": {
            "requires": "1.0.3-fabric,1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emixx",
          "version": {
            "requires": "1.2.3-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "emiffect",
          "version": {
            "requires": "2.1.6+mc1.21.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "lmft",
          "version": {
            "requires": "1.1.1+1.21.9-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "netherited-fireproof",
          "version": {
            "requires": "2.0.2-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.7+kotlin.2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "gk1henchants-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1henchants-fabric-1.21.1-21.1.1.2.jar",
          "size": 51107,
          "sha512": "017a4871fbb4cbb1c3f0f63e3e6edab096ff914fe0fc20c751c6ba29f58da319761515add21f409da955258b135fd01410caa63bf15075a4f8eed1a91e5f07e4",
          "sha256": "1fcfbc680aa08a1f4148b01445153f6b954925a5630b044dcf36b5842d7911bf",
          "sha1": "1c7ce77176856d8754ae444e8a4376254027c2a4",
          "md5": "451e53be67d1e4d2b010a5759a8baf75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1henchants-fabric-1.21.1-21.1.1.2-sources.jar",
          "url": "gk1henchants-fabric-1.21.1-21.1.1.2-sources.jar",
          "size": 23197,
          "sha512": "c56c2c1909c7acb533d6c78be6ebcde7febd8426b9bea9a6119ee4692a4958f64940b95ca6afc92fcfd795e66f71aaec5f4f08f5c7a7f28aac3dd00025fa0f3f",
          "sha256": "792e0d5d4f0d457356d3fc52de99b124b992dfd70aa2aace7ae154352acb8a19",
          "sha1": "7ba078b1e6daf465d5e224970940686d3fd545a6",
          "md5": "667d2390f4119cb8110fb94360f33bb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1henchants-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "url": "gk1henchants-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "size": 128668,
          "sha512": "88abb9a711b0e2bfbc9d633d3c159089de64f7fc0bbdadd194f5ef76394d4968532ba204229f5c0492e71fef04566e8da3dc0364871c806f92778a1a5fec4eea",
          "sha256": "8dde4aa7f9aa8c24b8d0c206e453c32752ff485ba55abfe2af8ba6ed15045e9b",
          "sha1": "a117ab5663f8c1c9a3a698457a542b793e07c137",
          "md5": "4343d89863743eed3d6a02afaccb6cf4"
        }
      ]
    }
  ]
}
