{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.7-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta1.jar",
          "size": 10613,
          "sha512": "329b0bd120f9f0e4cc57c74d5e7ac45897c92ed1f0ed868cde9351011d36d0ff0c3104ad0c8a86cf027fae4bb371fd0821760d44396a0c15e7cd3408088378ac",
          "sha256": "b23597ce9b643ece8fba68da84649c8bb10c25cf5b12888f9696e907969d14f5",
          "sha1": "ae5477e44b39df073116eb9ce68691af114653c8",
          "md5": "9221ce5770f03872efa238f09f7028ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta1.jar",
          "size": 10613,
          "sha512": "329b0bd120f9f0e4cc57c74d5e7ac45897c92ed1f0ed868cde9351011d36d0ff0c3104ad0c8a86cf027fae4bb371fd0821760d44396a0c15e7cd3408088378ac",
          "sha256": "b23597ce9b643ece8fba68da84649c8bb10c25cf5b12888f9696e907969d14f5",
          "sha1": "ae5477e44b39df073116eb9ce68691af114653c8",
          "md5": "9221ce5770f03872efa238f09f7028ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta1-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta1-sources.jar",
          "size": 7756,
          "sha512": "b0524207b6e7341e52842bcb5ed558f8f3cfcbdd5478a107f601a3d09e5207818957f39509d1b48fba5219ac8561c4f47c7eceaa08aa68a13d2c2c0b28178e83",
          "sha256": "9cf6c2f09af7a2258143f4625f36a9e0311ad696bd6cef335c149d38816ada25",
          "sha1": "445d5e856a1dac7b467d6d969bc5c53e059e6a14",
          "md5": "cf1384cc8ef2cc62043289210c41a144"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta1-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta1-javadoc.jar",
          "size": 107290,
          "sha512": "2cfdbc7a4e06b90645493c6b1d235223189d5f90db29912e4af00a809009f79e6ad10297209e51ac4dd30e21b19c922cc1790bce70a59a2d78761248392e298b",
          "sha256": "17fe913abf84ba072992d4d6b94032cdfac3a6c4903bbc653d016b5ec7228559",
          "sha1": "4e6e797586aa2108340f180f2c40c09eb82ee9b0",
          "md5": "e5f834b9fa37b4e47515128d3a269a7e"
        }
      ]
    }
  ]
}
