{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16611,
          "sha512": "2b17bc3bd4d93c87e063a9f3629b6ff116cc98a708c20b6e69b36943f157f420c08498167ac2b7e414b8282143a4c5bfcacae7e2fd714cbb2f33010a33eee144",
          "sha256": "5b52348a528c577b22abbed7e8a106ce514197c385dcc14dc7e0276b41131329",
          "sha1": "946d56c486d7c0077a6c5a45e6a23181ec704852",
          "md5": "67a400b291f0b327d9132297d661e895"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16611,
          "sha512": "2b17bc3bd4d93c87e063a9f3629b6ff116cc98a708c20b6e69b36943f157f420c08498167ac2b7e414b8282143a4c5bfcacae7e2fd714cbb2f33010a33eee144",
          "sha256": "5b52348a528c577b22abbed7e8a106ce514197c385dcc14dc7e0276b41131329",
          "sha1": "946d56c486d7c0077a6c5a45e6a23181ec704852",
          "md5": "67a400b291f0b327d9132297d661e895"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13154,
          "sha512": "a6982568ec050960b02e7ef2dccb5e6cfa399324a5ac71ef98093357c5e1fa8c4a0444af1384af0ae012ae81791a4a109ff933e6c89072acc68c8369b47fe929",
          "sha256": "859f65778a9132d6c509e2a501108f28b70b9b0ef19c7c42985b51ed101037d3",
          "sha1": "d58395f059791d605dbb8bee55c78bdea9ec9177",
          "md5": "dbf20b47d6df891a0de6fb1170e7a9d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 147760,
          "sha512": "728e1c3b1d83c3062cfd00d9b9660514424c860b29edf2d2a6abdded186897d00dbf47267870f38fe24f63fa438c9432690862dd65224e96f8738601dff3182a",
          "sha256": "b10d14c2670a65643013d50fc18250638616cf07eb19545455e8f1ab981df653",
          "sha1": "2b3c4b95d425e875d0c4627281ce76fc1f931b04",
          "md5": "bab7c613be5e2d2e8d8b7e547c1750ab"
        }
      ]
    }
  ]
}
