{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16679,
          "sha512": "d8e1b9723678596ee3b7ba298419a24fff2aea3070a886c2698158b99aff424efb49a370e11032e9ba82d5e4aac764a18e33ab1d34dd04f37e09ca24fdfe1028",
          "sha256": "e779078a8d39b9f2e4efb4efe52f615d4eb85e8150a2d93efb05080876e606f8",
          "sha1": "75fe068251b4856fa10ab866bd227c4fee042558",
          "md5": "f51b420e315c821654b688c6bec09942"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16679,
          "sha512": "d8e1b9723678596ee3b7ba298419a24fff2aea3070a886c2698158b99aff424efb49a370e11032e9ba82d5e4aac764a18e33ab1d34dd04f37e09ca24fdfe1028",
          "sha256": "e779078a8d39b9f2e4efb4efe52f615d4eb85e8150a2d93efb05080876e606f8",
          "sha1": "75fe068251b4856fa10ab866bd227c4fee042558",
          "md5": "f51b420e315c821654b688c6bec09942"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13209,
          "sha512": "4f50b5478f5943634c5a4b74ef43069fb9146cc1ffa7afde4144937a8036cd7b694be9b48583717e2927502d200ae7529dd33a2a619fde82e8353eaf992313c5",
          "sha256": "97e54950ffdf9177088e23f5de8925e02cb27b5ee371421b6e833927d85403bb",
          "sha1": "3397f8a763eacd78f30e99debf7b39aaeff5d68c",
          "md5": "2304ce04bdd885f74946384b0fe6c663"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 147918,
          "sha512": "04b872e8fcb5263359849327c408e5f925012ec0dcd9ad80a4ad010eaf6633999a523346e4711e5e987c267d1a8b69203075c017a8f4bfb23d2855cec1bc77db",
          "sha256": "5b1a0c14615c257dfe7cb4ecea3014f3ff9d44e17190386817419fd0a3d8208d",
          "sha1": "7d43b3da0e8158548e04d999c5270d9109e462c5",
          "md5": "23b471be4a98c9c53b0561fb37506429"
        }
      ]
    }
  ]
}
