{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16834,
          "sha512": "9e1b8796396795672671e577a74c8da9d751d0152c721a8cddd891db3a240a2a8de25ab408c4a6b9c8446a2ff9b0ee494c86382d34019be0e745e8f19dac7418",
          "sha256": "7a3f9b9d42c78ac9478cf841a92c08a1ebf663d16e73b8b11264596ad2284ee0",
          "sha1": "9745e5bf80c9b20ee06e31818529d105afcffdc7",
          "md5": "a5c5dbfae52e19cd8e400f6e287e290f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16834,
          "sha512": "9e1b8796396795672671e577a74c8da9d751d0152c721a8cddd891db3a240a2a8de25ab408c4a6b9c8446a2ff9b0ee494c86382d34019be0e745e8f19dac7418",
          "sha256": "7a3f9b9d42c78ac9478cf841a92c08a1ebf663d16e73b8b11264596ad2284ee0",
          "sha1": "9745e5bf80c9b20ee06e31818529d105afcffdc7",
          "md5": "a5c5dbfae52e19cd8e400f6e287e290f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13307,
          "sha512": "7982a3c1a77443b27f3d609bd41daf937009548a9572c8b24131c857dfce9534ab0bc10416bd8b2803b72dc0755cd9a610966195299af4a861f07c7d2ddeac11",
          "sha256": "1d99d83a20ebb5540afb01607e76c44a8cf93f0afacdada54a3cedbdde59a98b",
          "sha1": "39ee76bc60e2f3f0d59c202dda22e3a1844dc502",
          "md5": "31b1e6c6b2e644fd6adde9ab15445e7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 148250,
          "sha512": "1ac299786bbeae3ecfb95ebb4492a2d99ceb988a6382d57cf0475cc9eb15717d32478f503a1dfeef1e5dfac14146eebaf0d111f63d2ad2061919fc0331e2d2b8",
          "sha256": "cd4a1d69a2f321a7018e56b37e89cce143211d9ad02206d7c0cf3b80cd4b33a7",
          "sha1": "4c43fb0fc7d011dc0da373b3c77e006288f38df9",
          "md5": "c5eb079c74052b382df82575f068751e"
        }
      ]
    }
  ]
}
