{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16816,
          "sha512": "70bfadecd6c283acb270c3226fd6faa4ab26ad00e28abeac454ae3fff8afdafbe53a336c2fbe50424edd5f9831a14fc7045eab793e830726d51dffe3d3146b7d",
          "sha256": "ed0af3bd1e1dde8b412629e21b778fd567d45cd54382e4e806d3110cdabee193",
          "sha1": "89e583519fce022bc19b2062af45544908212db0",
          "md5": "a1b7a851e92f88cb47f80d6018a66600"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16816,
          "sha512": "70bfadecd6c283acb270c3226fd6faa4ab26ad00e28abeac454ae3fff8afdafbe53a336c2fbe50424edd5f9831a14fc7045eab793e830726d51dffe3d3146b7d",
          "sha256": "ed0af3bd1e1dde8b412629e21b778fd567d45cd54382e4e806d3110cdabee193",
          "sha1": "89e583519fce022bc19b2062af45544908212db0",
          "md5": "a1b7a851e92f88cb47f80d6018a66600"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13289,
          "sha512": "e30303831e8490aa39c7bf9094f1dc6019bac446e0605fb723d38224b1cece93d2164a2c0e53a30123e8e462b3e892d0b3ce666c188419056a19cddb521e5b8c",
          "sha256": "9938edea57acebc3bae24a4c8dc9bdd6a29b0fa193b6f1ddb25835d5a2adbfaf",
          "sha1": "4742e3426291da159b2bbfcb4ba770e5f07f336d",
          "md5": "8c3d67a215dc9367ef1c604358d4e694"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 148250,
          "sha512": "1ac299786bbeae3ecfb95ebb4492a2d99ceb988a6382d57cf0475cc9eb15717d32478f503a1dfeef1e5dfac14146eebaf0d111f63d2ad2061919fc0331e2d2b8",
          "sha256": "cd4a1d69a2f321a7018e56b37e89cce143211d9ad02206d7c0cf3b80cd4b33a7",
          "sha1": "4c43fb0fc7d011dc0da373b3c77e006288f38df9",
          "md5": "c5eb079c74052b382df82575f068751e"
        }
      ]
    }
  ]
}
