{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16928,
          "sha512": "89220df63984f663c5188d565eb9d80de73a6ee482bfb7b3747322e93509a7e343fecc0490ff83fe9d64d0a702e5c620acc29dbc53a716694a5b01d59ef7393c",
          "sha256": "45779d397e5e629dcb10211be2035afeb5ae289f1bb697ba6a964867744957d2",
          "sha1": "6bed1daf9a4b9f4642d8c69e14acabfb7c86d6e9",
          "md5": "f1296613a48cf1f9599f4e6837ee50d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16928,
          "sha512": "89220df63984f663c5188d565eb9d80de73a6ee482bfb7b3747322e93509a7e343fecc0490ff83fe9d64d0a702e5c620acc29dbc53a716694a5b01d59ef7393c",
          "sha256": "45779d397e5e629dcb10211be2035afeb5ae289f1bb697ba6a964867744957d2",
          "sha1": "6bed1daf9a4b9f4642d8c69e14acabfb7c86d6e9",
          "md5": "f1296613a48cf1f9599f4e6837ee50d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13377,
          "sha512": "5b8f0606ac5efb28cc24e48781efdea2eac2e4c7d63a966b1d3eeb44956519239485657521ddedaf7c6e8ceb256e73a940fef5e39c0cd61f44118c24f45ab6ae",
          "sha256": "60bb9ea0fff55cc243e9ee102d211edac7132f7bd4a4db562374d76aad1e3fc3",
          "sha1": "10f770cc9204457f89efb58072728f7cc258b02e",
          "md5": "6e7615572cc2a484488d256a82be96e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 148417,
          "sha512": "5aa3e243109cb2dc9a518d97986f72460b07d0d1223632a7b3997be7022cc9d1895125d67dc2f5a75e31cff212b5322ac909ce4dc4c157c6b1d69ca65cb61d2a",
          "sha256": "983350bbf5caf970c694c1ffa1fc49d623993cd55fce9f114fcc91f90d90aeb0",
          "sha1": "346176120bc4a34c00f0b5962a48ed8824e55548",
          "md5": "11a521745672ffe26f93468eff6e814c"
        }
      ]
    }
  ]
}
