{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16951,
          "sha512": "8759cb00521b84fd7f9714af4e69e160ecc813b922480a7e3d11dd7371fe6c1f8d6c5e9df6076f28a89a2cfae8e449af0fe94022927a34d26a17b83474848d9f",
          "sha256": "8d05f2b2c3544dc195730d0557e8352b05ea247cf1d66370303ee409a59f0d69",
          "sha1": "fd68a9f365c6ce698c25e03a2cf749689cb77495",
          "md5": "c96610f3ce2cfa168d9d54aaa5f6c2de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16951,
          "sha512": "8759cb00521b84fd7f9714af4e69e160ecc813b922480a7e3d11dd7371fe6c1f8d6c5e9df6076f28a89a2cfae8e449af0fe94022927a34d26a17b83474848d9f",
          "sha256": "8d05f2b2c3544dc195730d0557e8352b05ea247cf1d66370303ee409a59f0d69",
          "sha1": "fd68a9f365c6ce698c25e03a2cf749689cb77495",
          "md5": "c96610f3ce2cfa168d9d54aaa5f6c2de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13403,
          "sha512": "d45d0ebe45344379c5931fdfafc935f42f2b1f9b56ebbc00ae624ec170cfed5aa9f82d44507a7f25c42ce08528cff04a66b7c6ecb4d51677b50f7a353e7f49ed",
          "sha256": "b20639d2ce6bcdd6bc87756654af18a3ea39cd1efadbca0c4f8e035f056be2a9",
          "sha1": "5c1e9a98239b4140efdbeead7a5570c6258a98bf",
          "md5": "d5742347aaf96f96848203c59622622c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 148527,
          "sha512": "35f0f3e6fa726129307cbdad21bcf20ad90870a8dd20e650fc2ff3d6cc194624c6cfb56235e39656da248677d2d102e772ec5f9bd24a2de1ec1ef24f461b8606",
          "sha256": "e4cc0f944ebb01ddcfd38fcb5f945187ae74c541de40b068a4c52ca424aede9c",
          "sha1": "244231bf6253b8824d08d5e745c2791c034b2ce0",
          "md5": "241af52ecbb61aa73adf60a71a97b78f"
        }
      ]
    }
  ]
}
