{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16713,
          "sha512": "2f01e8234ed180f0535518292dc2d2c25b94d956c4e5f77106e7d04f1574a1662cffcf69686c390c7fdd1516e5298e906950203cc18205df88d43a5516ab6e1c",
          "sha256": "91f852f53599731a2b7fe5a7e2b541a17ce0ba02c4db8c74b1a0d86a01f4121d",
          "sha1": "bf9af393ed4cf7a286ffee9a10975770685199f7",
          "md5": "e54acd196e81018cfda04156ca1e192a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 16713,
          "sha512": "2f01e8234ed180f0535518292dc2d2c25b94d956c4e5f77106e7d04f1574a1662cffcf69686c390c7fdd1516e5298e906950203cc18205df88d43a5516ab6e1c",
          "sha256": "91f852f53599731a2b7fe5a7e2b541a17ce0ba02c4db8c74b1a0d86a01f4121d",
          "sha1": "bf9af393ed4cf7a286ffee9a10975770685199f7",
          "md5": "e54acd196e81018cfda04156ca1e192a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 13231,
          "sha512": "de52aff5dd5c5eac474bdf6b08fada97b5e29de922f7d7a66f2d105ea49babef20f8a1ffc5df7dcfbbe20263828eb2f1181b69650c7a5102bff54a736fdde383",
          "sha256": "cb5491eb86607f8a2806f276217d451a1ad69248135fc27a1b523e36681bcbe1",
          "sha1": "d9c311746d3ff2eb6e7aa6f98fa3f9e5555d2e72",
          "md5": "3f1c3f87e23b0b21ad96364bd8705dc8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 147996,
          "sha512": "e2f3e3e023b0e5d65255fc8c5f6ee1ccd151b45e818ccc63fad735dd4dc679a37284a49d869fb32d0608009dc1feda372beff69aff04dc63da975ca4ac24b99a",
          "sha256": "f4dd4cd1dbe1c86b7d879ae6012c9d7f2a44cca5970553ec974f7d35829dc431",
          "sha1": "c49016376ebb067f6d42ac1144180f11ba50b2da",
          "md5": "63e200b96dc87616b7304b98676dcf16"
        }
      ]
    }
  ]
}
