{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hextras",
    "module": "gk1hextras-neoforge-1.21.1",
    "version": "21.1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-neoforge-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-neoforge-1.21.1-21.1.1.1.jar",
          "size": 24664,
          "sha512": "342f7ddbf2eb34f78b594cc4887a7e4b7a0856e9163dbc704b8bc2517983fac616bc9b8d8f9e2c82cd008bc2998241849edb34b7dfa0a198b1a96ddb375dc4e2",
          "sha256": "3ebecf14ea9b19866b49fdad46b8bea9d5d622eac7e6c5f8a4554a9e7bc37da2",
          "sha1": "94b3837e6634f70207c9d9969d7b3e739387d392",
          "md5": "31797fbf159851deae76e7bf9039b2fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.4+1.21+neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ender-zoology",
          "version": {
            "requires": "v21.1.4-1.21.1-NeoForge"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-neoforge-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-neoforge",
          "version": {
            "requires": "21.1.39"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sword-blocking-mechanics",
          "version": {
            "requires": "v21.1.1-1.21.1-NeoForge"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-neoforge-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-neoforge-1.21.1-21.1.1.1.jar",
          "size": 24664,
          "sha512": "342f7ddbf2eb34f78b594cc4887a7e4b7a0856e9163dbc704b8bc2517983fac616bc9b8d8f9e2c82cd008bc2998241849edb34b7dfa0a198b1a96ddb375dc4e2",
          "sha256": "3ebecf14ea9b19866b49fdad46b8bea9d5d622eac7e6c5f8a4554a9e7bc37da2",
          "sha1": "94b3837e6634f70207c9d9969d7b3e739387d392",
          "md5": "31797fbf159851deae76e7bf9039b2fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-neoforge-1.21.1-21.1.1.1-sources.jar",
          "url": "gk1hextras-neoforge-1.21.1-21.1.1.1-sources.jar",
          "size": 18457,
          "sha512": "07ccd12735b362219f3e099e4e1c13edb3a0a35feb7487208c1ca1798a3b79e4ffa3bc8a84a4cbf3ed5a58d1857126a02b9560546c44270a393563ff60cf59c1",
          "sha256": "0ba4c8ce76b20ab7029e2be401d4a2b9b5c8a7a20fbee9162baa43411002a4ec",
          "sha1": "254d2608d1874b037eb1df969729163880a556fe",
          "md5": "cb5d289a788252af42f6841cef1fdf3e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-neoforge-1.21.1-21.1.1.1-javadoc.jar",
          "url": "gk1hextras-neoforge-1.21.1-21.1.1.1-javadoc.jar",
          "size": 151400,
          "sha512": "8abb556faea7a7d1bf573b42025a3d488155d7f7e981532dad15be0170ff41024b2c90a89da52a36fc8e7b858d7d9d813233e89c406fd4a74e407097a9b311cf",
          "sha256": "3fa8e9b990fa6066b3efaba1ff921ed566b598625e4bafff1be2b2e9152bc5e3",
          "sha1": "046a6430107eadf2d37409a4965cce462f8b1555",
          "md5": "3fabcf109da6cc6273d838805711e53b"
        }
      ]
    }
  ]
}
