{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.2.jar",
          "size": 11470,
          "sha512": "443ee6173164137bb787b0be79fb9cc90833cbd9cb806eff073366df58d59d5bab84c05b8bfb457419e9fa802309eb65d1044adbdac1f2dae8b2a0939a673e00",
          "sha256": "2698fabfb948938ad1cf103b915e590c19a52462b19084e554a8d27d0662aef9",
          "sha1": "20466acab13fd73ddb8ff135a63f2e13330a101a",
          "md5": "0a8990ec51e2fdf8316a9d9a5cdaeecf"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.2.jar",
          "size": 11470,
          "sha512": "443ee6173164137bb787b0be79fb9cc90833cbd9cb806eff073366df58d59d5bab84c05b8bfb457419e9fa802309eb65d1044adbdac1f2dae8b2a0939a673e00",
          "sha256": "2698fabfb948938ad1cf103b915e590c19a52462b19084e554a8d27d0662aef9",
          "sha1": "20466acab13fd73ddb8ff135a63f2e13330a101a",
          "md5": "0a8990ec51e2fdf8316a9d9a5cdaeecf"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.2-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.2-sources.jar",
          "size": 9380,
          "sha512": "9b75a96ef1e1ede6868075097ad18daa41e0a4aff12e46f8210730e4e42ba152a3f54301ab5ef44379ae6d4a11c102803d93a49782d1ac5dd18677c44205f1e6",
          "sha256": "4bb669d17ef8ca51fd0c43fef806a03d73ad953c6ed258da517aa633d0cf8f05",
          "sha1": "4865afa594eaaa58cc514e015dc0865cb885107c",
          "md5": "1f40597fe56d18c7920b7891124b9b30"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "size": 108598,
          "sha512": "550cd0da9a18037f18a42bb57259bd88e1e0bcd4db6ace6cf7158695b75d6ede9b902612a98e0c7b074cb958fe3422ece2c25032ededa5f0ccd21ffb2d096900",
          "sha256": "e543bd94ee2913e1a4055b1a49d6f762ad1976bbc8187c72a88dbf366d94fad7",
          "sha1": "72a7b2649bfa48e8a403b1dd1586102520948637",
          "md5": "6175971262338b9ff79bf7a71be89b67"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore-fabric-1.21.1",
          "version": "21.1.1.2"
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "name": "gk1hcore",
          "version": "21.1.1.2"
        }
      ]
    }
  ]
}
