{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htravelersbackpackplus",
    "module": "gk1htravelersbackpackplus-fabric-1.21.1",
    "version": "21.1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2.jar",
          "size": 9977,
          "sha512": "8d7d8c913ace35c799ba0cdfaf982033f5ba47e043e46b37439a16ec0d7e1bc1060bc6f3220c31c89d8dc7dd9ad2f93ed03a6f9d8c559d0a0b6dc7a90b918b99",
          "sha256": "6467593a9855e3a1e3db6e6f7bbd5a11ccd2e7ce2065859547b1084c86449969",
          "sha1": "e9afa673446b513522c53f0542467715fe73d8b1",
          "md5": "a6cb4f45019d46f263ab80da34ac1e32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-fabric-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "travelersbackpack",
          "version": {
            "requires": "1.21.1-10.1.29-fabric"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2.jar",
          "url": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2.jar",
          "size": 9977,
          "sha512": "8d7d8c913ace35c799ba0cdfaf982033f5ba47e043e46b37439a16ec0d7e1bc1060bc6f3220c31c89d8dc7dd9ad2f93ed03a6f9d8c559d0a0b6dc7a90b918b99",
          "sha256": "6467593a9855e3a1e3db6e6f7bbd5a11ccd2e7ce2065859547b1084c86449969",
          "sha1": "e9afa673446b513522c53f0542467715fe73d8b1",
          "md5": "a6cb4f45019d46f263ab80da34ac1e32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2-sources.jar",
          "url": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2-sources.jar",
          "size": 8962,
          "sha512": "fd953224d76d450dec4e0c709267fe82835b972d883217f5a1206857232d3fdbf28585e5ab52f3dbbda0be94bbdcfc008de8fb4ac4f8da4b3816fcfe2b31c4ca",
          "sha256": "f4e47fbd21ee6acfeedbdd84294800c459066b55c77fa13346b520649cdca9d9",
          "sha1": "852b196fa52bb3f2812128098697d693dd61f01e",
          "md5": "7d1a3af19c89ee3de88e33f24a576630"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "url": "gk1htravelersbackpackplus-fabric-1.21.1-21.1.1.2-javadoc.jar",
          "size": 104108,
          "sha512": "35be9b050837af69abec343dd1dc39169f1a167995b047e5e4bf57e410c746cfaaad3eac7c02b58442064a160dbf38fc544af31a91fdb10cf4f71e94ff0115d3",
          "sha256": "9a89548d6dd2e28832067a2efb541ab30f29bda9d61e283fffafd8077a7b84f9",
          "sha1": "b66930465cd078d89fc287915afb02e65a14b2f2",
          "md5": "df02b8f0d474d8d0c3be0a17e69cfd26"
        }
      ]
    }
  ]
}
