{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 22083,
          "sha512": "81078a7582109ae73bb983f6681ab379e7a7f2f70744009fd118e6dfa5cb729d85afd0bafef3292f38eeab7ab65f7eeb87b9660cb71929e6bd6b7b559d2c33be",
          "sha256": "5219cc6503de001edb1754b4ba34a0c646906c1343198cdc3234d8fb52eda3d7",
          "sha1": "ab7f2cae3ec8c0b9ca7478a6bfc880ed44b24c9b",
          "md5": "26111f409ece1a14a3b7dd59a5fbe660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT.jar",
          "size": 22083,
          "sha512": "81078a7582109ae73bb983f6681ab379e7a7f2f70744009fd118e6dfa5cb729d85afd0bafef3292f38eeab7ab65f7eeb87b9660cb71929e6bd6b7b559d2c33be",
          "sha256": "5219cc6503de001edb1754b4ba34a0c646906c1343198cdc3234d8fb52eda3d7",
          "sha1": "ab7f2cae3ec8c0b9ca7478a6bfc880ed44b24c9b",
          "md5": "26111f409ece1a14a3b7dd59a5fbe660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-sources.jar",
          "size": 13890,
          "sha512": "30988241e1400c51cf55ae4f413445fc89d7f16f86ee49a7eeab877812e756f99055a554a163ec20705e3c8de21b1fea5e19d0e028d54a43653769cd83b92f5c",
          "sha256": "afc94a756a2537719320a38fdb74a94d94beb2d4a6f76772bbcf5d6159ce950c",
          "sha1": "a17f958bbd2b27e87b372c4a899b27d3556991f2",
          "md5": "d9bca8f4a5aabb48d3be1e1c71f70040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-javadoc.jar",
          "size": 140907,
          "sha512": "7ce2b106e1a9374ee23e27375cdeb3c67244c028179626e0496f15154df053cf4f3f7d3f0806c1fb3e1a24adbe5b79f868756032f3087c908e4fdb007539a577",
          "sha256": "33f5e878dbe674fc5e9579082bca519bf617a9747ba04a4801224b54005a264f",
          "sha1": "62f987b7d195206d8213719fef8965086ffa3fd4",
          "md5": "806afbe1ac5735562ca2e15177ad6698"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.8-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
