{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.4.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.4.jar",
          "size": 17641,
          "sha512": "754986a10afa6b69d63e73f1fb80c62456abbc851b3657196798b024adc6a8c92c41079ea20c8a8c7051afafd6d5decb1fac6ea8347cdaf8fa705e35761a1597",
          "sha256": "3a28147482c7315a1068dba6340f81835f6e38e9482913a4af16005d89039868",
          "sha1": "ef1cc1bf0fdd203b92a7e2fc37473883c3ab0b15",
          "md5": "469b4b3d55b8283ca1c23eae42b0a105"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.4.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.4.jar",
          "size": 17641,
          "sha512": "754986a10afa6b69d63e73f1fb80c62456abbc851b3657196798b024adc6a8c92c41079ea20c8a8c7051afafd6d5decb1fac6ea8347cdaf8fa705e35761a1597",
          "sha256": "3a28147482c7315a1068dba6340f81835f6e38e9482913a4af16005d89039868",
          "sha1": "ef1cc1bf0fdd203b92a7e2fc37473883c3ab0b15",
          "md5": "469b4b3d55b8283ca1c23eae42b0a105"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.4-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.4-sources.jar",
          "size": 11801,
          "sha512": "bdd2bd98a40c7640f0c5f86957e19634f4edb85aca876031ca7bc501ee3bdfef2ec00340b61b1d49124e1ac123d112cd6c130e316eca629cce6cd96004fd7cbe",
          "sha256": "73fdd4f326ab97d38623e668a52b7f84fe16bdbd8194e59f2f4c86d4814aab53",
          "sha1": "d4f4805341c99131f1b82e23cb49e47f7ce0d122",
          "md5": "be65d99662e3daa6141d3c9d82257d6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.4-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.4-javadoc.jar",
          "size": 123069,
          "sha512": "6376bbb25f5e35284c545e97eabb0372c858a78126bbf065848fde1b7aa62136b21c40a192e05c6fe72522b264c1b824bb513256fcea4c69329d6d1d8a3c68a7",
          "sha256": "694bf5f79beefd62b14d2efd372b5fbeb8c27ff70176d0d9ce30e7b9e1b3a652",
          "sha1": "b72d43849f6c540096362fdea9caa815413544bd",
          "md5": "804b15a77ec8789d466fcdda1bd9f7ce"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.4-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.4-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
