{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-fabric-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 17187,
          "sha512": "b1ff36433090051909b32ec54259d62e01c864d45cc8fa57fc9c33cc755ec6ed3e976985ddc3eeda3e2f470e82c00196f7e62ce1e3a301a10295020107d873fa",
          "sha256": "9f40388186272493ac25f96576d02ae0f37768629a7ba179cf0316b9a9df0195",
          "sha1": "81083918f59108b7633907f912ac98b811471f19",
          "md5": "18ee7cd7c5562a219cafe7609110c522"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-fabric-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 17187,
          "sha512": "b1ff36433090051909b32ec54259d62e01c864d45cc8fa57fc9c33cc755ec6ed3e976985ddc3eeda3e2f470e82c00196f7e62ce1e3a301a10295020107d873fa",
          "sha256": "9f40388186272493ac25f96576d02ae0f37768629a7ba179cf0316b9a9df0195",
          "sha1": "81083918f59108b7633907f912ac98b811471f19",
          "md5": "18ee7cd7c5562a219cafe7609110c522"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-fabric-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 14071,
          "sha512": "ead5620f295676519324e9846ac455f1c606248ce3945b4ff00f0dbad95106035da3d098ab53e85583a2d9b65504e5d685d9a607864dd4a3e6379b666c7e927d",
          "sha256": "d0859969604693108c64a66fd708b97f5339352df49c2cec52c2162dacc6cbd5",
          "sha1": "06052006ae906debc1c7ef10656ee4507b6caba1",
          "md5": "d453a9708907df67336b8b8b59d7b55d"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-fabric-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 121545,
          "sha512": "46fa6b026c56dde2519903092cc35f749ab5d7a235cd0f927ff1c4723968c51d3425c11e46eedf95dff909d0fd48718ebbd9b0209d7ab1c9b3ce7aeb6fa41420",
          "sha256": "bcd7f2725a403bc71a201eb5d5beccaa17df40471baf0c3c72aed85c3a81a2c4",
          "sha1": "2072daf7b2b34b7a52273c82986666c3fbfa7d2c",
          "md5": "19558bddf7b5c70b58ca0f10af5c47a7"
        }
      ],
      "capabilities": [
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags",
          "version": "21.1.1.0-SNAPSHOT"
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "name": "gk1htags-fabric-1.21.1",
          "version": "21.1.1.0-SNAPSHOT"
        }
      ]
    }
  ]
}
