{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1htags",
    "module": "gk1htags-fabric-1.21.1",
    "version": "21.1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 23759,
          "sha512": "0db9a2e057860d40115c5b75b41097fe225d430b4e56409cac079feb86309c2163db3df4093411cb6b82f0fb46ab8e30742526de67712fdf877bbdb968c5c101",
          "sha256": "33d23720e005fc81eb471f2df39b0da32ac8604bc7a1c0b0b18375dfa897e486",
          "sha1": "f3f13ca92cc5a174bb0a0aa808cd6467ffbe733d",
          "md5": "39cb4854637564be56048e1634e4d8fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.2-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT.jar",
          "size": 23759,
          "sha512": "0db9a2e057860d40115c5b75b41097fe225d430b4e56409cac079feb86309c2163db3df4093411cb6b82f0fb46ab8e30742526de67712fdf877bbdb968c5c101",
          "sha256": "33d23720e005fc81eb471f2df39b0da32ac8604bc7a1c0b0b18375dfa897e486",
          "sha1": "f3f13ca92cc5a174bb0a0aa808cd6467ffbe733d",
          "md5": "39cb4854637564be56048e1634e4d8fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-sources.jar",
          "size": 21163,
          "sha512": "1915bd66e5ba27b4bc6f9e0dc6f0c2d2bd739f5c572aebeeb1e2e1ef2bc47c04ec37907a1ed67fb6000f800451f3d3ff2707c48ef7c7227809cc5baf29d2375a",
          "sha256": "2020d12ea7ddee3bed4df0c9e4eda877bc37b0c2383dbb81d097cac6ece9ca0d",
          "sha1": "c1aa5ba4d8891707eed27059fcc978a6cd1654d5",
          "md5": "e66c78f04336eddf4d3d4e1e79be7916"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "url": "gk1htags-fabric-1.21.1-21.1.1.0-SNAPSHOT-javadoc.jar",
          "size": 121890,
          "sha512": "182e850760e384fdfbc06acf5cb1d4259ef58a3cdfc274642a12db76cc6fe9da7d093a217ced0eab756db8ef2d7014dba59e7c79042077c05274f55600270a00",
          "sha256": "1ede364d8884b74571b3175c666bdeddfd5f3a5be7b3ef21534e3b34875c6ef9",
          "sha1": "71f69e40ebcfc9d7a85f54a2710d0f89cd1e6bb9",
          "md5": "36bc4f5c19b7fee66bc8f59afcc8f726"
        }
      ]
    }
  ]
}
