{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.7-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1.jar",
          "size": 16721,
          "sha512": "75da5c9cdeff05284065fb7699aae7792435a6f0af5c200db30a822aa8c469c425983e8ae1b00c978e6fa0b710c1f87056905b37a3343ae6adf4f86f4d6c7974",
          "sha256": "089aa0d8a2319e21728533b4588c82b95c7c40c313ea7e76e271053fc85beeef",
          "sha1": "145e09e70ce38f280d11ee0f00977dd71c5be30f",
          "md5": "3672d2931098076dcf5d090345e199d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1.jar",
          "size": 16721,
          "sha512": "75da5c9cdeff05284065fb7699aae7792435a6f0af5c200db30a822aa8c469c425983e8ae1b00c978e6fa0b710c1f87056905b37a3343ae6adf4f86f4d6c7974",
          "sha256": "089aa0d8a2319e21728533b4588c82b95c7c40c313ea7e76e271053fc85beeef",
          "sha1": "145e09e70ce38f280d11ee0f00977dd71c5be30f",
          "md5": "3672d2931098076dcf5d090345e199d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-sources.jar",
          "size": 11964,
          "sha512": "6d11229d4a9f3be6e2c6da58e54e3c64390585291b3a73ea5814cfea379e98cad14dc3df773b4b319776bf009ee0be20e2883a389762c990517a632ac8667e06",
          "sha256": "4f5cbce4fc923ad8ff3ae523cd057c2faba50a7b974e79f1ff28d4261ee98fa2",
          "sha1": "864b4c780c2b21de6c5adb3a79ae9becace16bd3",
          "md5": "ac173dd2b6fa4bd71fc3e10f494c7a3d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-javadoc.jar",
          "size": 116173,
          "sha512": "51b01039d65d34a5343bec614b5fa0096c2adcea80a414cdd41b7e63530e3d4546fe53bed12a50c19bfa8d362b9eb04d829e171f5ae36fd988b5398671ead4b6",
          "sha256": "e3e93b83263b09ccc531adcc9f6e545626ccfef94d944d1412d34fda1d7e751d",
          "sha1": "5c35eec05ef692bc74668baf5ccb2b75dad95f38",
          "md5": "b8b7d155a00406de127801b9be798809"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.7-beta1-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
