{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.0.jar",
          "size": 15611,
          "sha512": "1fa4326ff1677e5768054bc71be7d25c252980a35cd6b7d09c4a18a798e78dde33adc28a4b087abde82735ea2c06f2421cac96bea95d151d8e5ac51c50a1eb2c",
          "sha256": "abf9ceb083224982db14a0a7b702666ed6a9546f07b9401e2e562bd414e55ca6",
          "sha1": "4230bb83c3a48b950f321fb1e7e6e46c55f70a56",
          "md5": "aaeb0aa0ec90a3207d719355ebcf6a49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.0.jar",
          "size": 15611,
          "sha512": "1fa4326ff1677e5768054bc71be7d25c252980a35cd6b7d09c4a18a798e78dde33adc28a4b087abde82735ea2c06f2421cac96bea95d151d8e5ac51c50a1eb2c",
          "sha256": "abf9ceb083224982db14a0a7b702666ed6a9546f07b9401e2e562bd414e55ca6",
          "sha1": "4230bb83c3a48b950f321fb1e7e6e46c55f70a56",
          "md5": "aaeb0aa0ec90a3207d719355ebcf6a49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.0-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.0-sources.jar",
          "size": 12452,
          "sha512": "43c452e1ace14b4cbcb338464d7440ed69cc17800333c35f519fd46c1e8e7fbe19a830fb0e06d17be2e40852b244c093b5e021d9512d5f38a0df258929866f16",
          "sha256": "32e648f7b27811f15c3a3bda16f88632283f336c7b00c323224fc11c30a3aae9",
          "sha1": "2670000a2b841e7f914835eb5da65a633bdcc194",
          "md5": "57fdccae6d308b7726eb4453445952f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.2.0-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.2.0-javadoc.jar",
          "size": 141024,
          "sha512": "92eef734f7210095b482a0515dc3c68d992fe3ce98a9d302ba59b39f063e17144c140eb56ef9833058e864e690cb05434cb44346a6b8129b9805053703081039",
          "sha256": "e0edb52e88cd733dba997a7f957f02b7adf57a826f798d1d7fc2e7254da126fc",
          "sha1": "bd498b3d0a254017392d7df29bb0e217ef29ec8d",
          "md5": "5ebc8df3679d9b32c4f58ffb34242c32"
        }
      ]
    }
  ]
}
