{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4.jar",
          "size": 18574,
          "sha512": "5b4fcbc3bd544cff936ee76242d3ece83cfec4a99700d8c9b27a16f16292728f71da1aed030e00b0d919a53686bd9b6aa558f3dad61331bfdc82b641b21dde88",
          "sha256": "5f0cf7f2f44551ef09923b4d3ad6a0f99b37ac6e02afac56d240c157f6525009",
          "sha1": "1048b64ac63c86c64e5f5af18322804734595c96",
          "md5": "8e8fdd27a5c4807d53fb27f4475bd78e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4.jar",
          "size": 18574,
          "sha512": "5b4fcbc3bd544cff936ee76242d3ece83cfec4a99700d8c9b27a16f16292728f71da1aed030e00b0d919a53686bd9b6aa558f3dad61331bfdc82b641b21dde88",
          "sha256": "5f0cf7f2f44551ef09923b4d3ad6a0f99b37ac6e02afac56d240c157f6525009",
          "sha1": "1048b64ac63c86c64e5f5af18322804734595c96",
          "md5": "8e8fdd27a5c4807d53fb27f4475bd78e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-sources.jar",
          "size": 12948,
          "sha512": "537d544f7f70a50eabf31a44a4c6b4c59d9ff4120ed816a8b14729badf6f2e49f36c5da4363b4a7a57ecff5773b75eaf0e967a68758468b400c6c29f6d8590db",
          "sha256": "bda0c791bceab27feeef115473f2c4ffa134c00e1c0b39fbca555df15257fb25",
          "sha1": "fe6c0892a2ffa84168a643860225f15f92abd150",
          "md5": "00f8446b64201a9814c8c5c71cbab1db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-javadoc.jar",
          "size": 123195,
          "sha512": "1bd26c998ee4df251e9945740508e2f32c1b8d1c5e35a9a99d3f52df6962f6452f2f619c9812567a9b17a777452e060783402a78b01b4fe5e6f99421be550d98",
          "sha256": "f4ccf55d90ddd39239d27c1c493736f34b4bd9430172b1ac7cb26d76632474f3",
          "sha1": "dae12229cd1d301acef7ee5c061b31e232e923f6",
          "md5": "1e25cf3a3ceb617d9b939163832ff295"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-beta4-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
