{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.5.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.5.jar",
          "size": 17671,
          "sha512": "47e1ca2f2301b427d9175375a4262dd3b4f7d7039f9a8e4d35e1f923c638bffb4f9bcc607c060c4bfd1e09f071c9c28fea22af307d05be0de1e28a22bc6948f6",
          "sha256": "1b3e1705327f6c4b8aa4bd450a8abc72bc42c79203b954c701921ad043241ccc",
          "sha1": "dbc5c7933a16f28c18669c277c7704ddbc72e547",
          "md5": "033f3bbed3e110c24f3fd4bf79d0fa77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.5.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.5.jar",
          "size": 17671,
          "sha512": "47e1ca2f2301b427d9175375a4262dd3b4f7d7039f9a8e4d35e1f923c638bffb4f9bcc607c060c4bfd1e09f071c9c28fea22af307d05be0de1e28a22bc6948f6",
          "sha256": "1b3e1705327f6c4b8aa4bd450a8abc72bc42c79203b954c701921ad043241ccc",
          "sha1": "dbc5c7933a16f28c18669c277c7704ddbc72e547",
          "md5": "033f3bbed3e110c24f3fd4bf79d0fa77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.5-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.5-sources.jar",
          "size": 11953,
          "sha512": "26b40e44af0930eb87f7d8d40f61bf3a5682f1b42bcc5b1af1a39f9d003b774dbea64cd0406e9fd55af476bd39e0aed38116fb8690426e0ed19114d67c04b4be",
          "sha256": "e25528b7ec63681c986431563b2486db8f8d2d5c1e8cef14559037a00c986746",
          "sha1": "e33964088cf06ad987411f6b58516fa08a982993",
          "md5": "52ef8d383a7a0cafa99e69672243e0e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.5-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.5-javadoc.jar",
          "size": 123055,
          "sha512": "9a7c84682fa812f076d3059495b93030337ec28964366b08547cb1406c299ec64d92b4458ff3acd6a22ffaaae8b8e239bc04d0e7bf559b01f06a587017bb1781",
          "sha256": "898625934b0178b1b30c30178755262a2f49c52122d1f48233d2254a46a0e1d5",
          "sha1": "b894ff5a91b8f46416764fc9c852713da5e79dcd",
          "md5": "7ca3af8eeb42c855d684923ced1bfade"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.5-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.5-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
