{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.6-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1.jar",
          "size": 17870,
          "sha512": "ff66c8e5a16a8a9800c3e34218e7456d0cddf0d08618ff6ff5056be920bcc50beada9be0a188526216250af9bdc6d6dea8575915a38f968d84c573aaff8117da",
          "sha256": "6d361c6afdc6b2cace5ed4ef158b7874d8b86c77319a9d04e252df0dba2a6fe5",
          "sha1": "e8c695745051e8dd39751fe9ed6b6335ecf61367",
          "md5": "b21c7152f1c42f9bfa0f1bf9a43b4009"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1.jar",
          "size": 17870,
          "sha512": "ff66c8e5a16a8a9800c3e34218e7456d0cddf0d08618ff6ff5056be920bcc50beada9be0a188526216250af9bdc6d6dea8575915a38f968d84c573aaff8117da",
          "sha256": "6d361c6afdc6b2cace5ed4ef158b7874d8b86c77319a9d04e252df0dba2a6fe5",
          "sha1": "e8c695745051e8dd39751fe9ed6b6335ecf61367",
          "md5": "b21c7152f1c42f9bfa0f1bf9a43b4009"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-sources.jar",
          "size": 12023,
          "sha512": "f25a04dacd14db196e54a9d0c0c8dde623d462e7cf282329a82840915668be5e15df913d2385f7a7e0f32be5c587c498da163bd5426866c431fef67b7c3da2fe",
          "sha256": "8f20eab83293aa135e491030495436d47b3b9e376a3a5fb3853fe1757b260212",
          "sha1": "a0b90186d43d81b99a612c830311fc6cd354eeef",
          "md5": "f614e3e70b185459c0cef1ef51138af3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-javadoc.jar",
          "size": 123572,
          "sha512": "7a32897b48cca0341827073f5b84d2e9663b3dacb63910e100defe1b26876124c0a7a661a2d8df6d286adc91273ff8b0836858777705b91787df412c8fe63bbf",
          "sha256": "358def995d61f7df56dac6398aee3815e79ad27a14689415eb4fa10128dd9e01",
          "sha1": "6fcbd57cef3d3a5b50933f0241a6797660cd5715",
          "md5": "f0634c202ca6a468662f5b3277310bab"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.6-alpha1-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
