{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.1.3-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3.jar",
          "size": 11390,
          "sha512": "50191ae7bf58ef91c8b5bec7d151f6326a611b1ea4d720bc18500c1c127824db1ac8e64710340a1ff7d4cc102788a315321f27acbde36a0885f328f8237cff3e",
          "sha256": "2310193e303a20cba43f42b550ee05d885471d49a8ba8c3a1b8c37044b0ebd8f",
          "sha1": "a89f308273de971baa5e0b2c9434d73b436333d0",
          "md5": "8f71608bd8093f8eb5308111edec811d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21+neoforge"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3.jar",
          "size": 11390,
          "sha512": "50191ae7bf58ef91c8b5bec7d151f6326a611b1ea4d720bc18500c1c127824db1ac8e64710340a1ff7d4cc102788a315321f27acbde36a0885f328f8237cff3e",
          "sha256": "2310193e303a20cba43f42b550ee05d885471d49a8ba8c3a1b8c37044b0ebd8f",
          "sha1": "a89f308273de971baa5e0b2c9434d73b436333d0",
          "md5": "8f71608bd8093f8eb5308111edec811d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3-sources.jar",
          "size": 9367,
          "sha512": "8c145e2b86424b0f6a4926a3f50a26391ab815ad92804b3d2fabe531a8dd807503932a15f2933e84e75e47f03c2cd5ed1aa15af41af87a61af675dead5b37feb",
          "sha256": "0a5140ca91d1a835d3dde8078fed0db93d72164a4bd78c21cd4ea2f9bd614c6b",
          "sha1": "5308bbd121997aa1429ece76f8f9fa576141a61a",
          "md5": "879663ffab1e5ed8d89dc9d14f2d3001"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.1.3-alpha3-javadoc.jar",
          "size": 108257,
          "sha512": "ae3cbca9a1ba7e31467a4ab6ece819d4c588cc900b48fbdc82657c5649acba203fc93edcafc71eaa565214995ce14afebd1052affa58445684ba5c3ba529e1ee",
          "sha256": "9b6a7046b2d9dcdf3ca608c61fe8d7d19b7e8679c78f8ff09be9d2d408b48df1",
          "sha1": "9a6cde3e4d8ac8ed0611592a7ae4049f1fd69d66",
          "md5": "2248ec060c6dc6332dae68b84d191293"
        }
      ]
    }
  ]
}
