{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.7-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta2.jar",
          "size": 12931,
          "sha512": "c6bed4f38662ffb237b7b3541b89881c6b8c8698c3e7d5ea7ece73811148495d6d9464a13312fb73226db8cccf23becb1171384447f1ba8289a478dadca706ce",
          "sha256": "b41a350c580b739b82fc615768b0517006c9cd350b7eef00de866c7d489543e2",
          "sha1": "5c690a2659585e69400ec944dec13bf0ce54bba7",
          "md5": "5b4e490c40a128e7aea0d1e6a530c687"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta2.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta2.jar",
          "size": 12931,
          "sha512": "c6bed4f38662ffb237b7b3541b89881c6b8c8698c3e7d5ea7ece73811148495d6d9464a13312fb73226db8cccf23becb1171384447f1ba8289a478dadca706ce",
          "sha256": "b41a350c580b739b82fc615768b0517006c9cd350b7eef00de866c7d489543e2",
          "sha1": "5c690a2659585e69400ec944dec13bf0ce54bba7",
          "md5": "5b4e490c40a128e7aea0d1e6a530c687"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta2-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta2-sources.jar",
          "size": 7967,
          "sha512": "5584b25e5cc8987d77333b3a0c08a4c33afaaddc70da25bc2c111e70cfdacd65fb7f05e0e5c1fd13b32103f548ee475572582c3c6d014a02d789a95564560002",
          "sha256": "299f832d4c9bc238bf746377978eac8b4555ddd3b5375fc30afe09cb0f78cef2",
          "sha1": "0cc8b766ffdc1d7c7f67b1e1935450978b848878",
          "md5": "00fb72789d09af21fa2cbcdca75d35b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.7-beta2-javadoc.jar",
          "size": 122103,
          "sha512": "3ef283fdd86e3a07d9ea4e0ef105ae7cd3831410f1d419fc3098f7f59222b3cc2cf6cb739996bf538ed8c45087cd62e3059c44fb35291d2e9aeff077879a23f5",
          "sha256": "35d795304d41b36cf22b02a98adb99530d022dbee7b22d59cd5f12ac65c228ed",
          "sha1": "1dcf7df3377dca6a571464dc538b23b86f1b2610",
          "md5": "1bb494daabee34ea31629b14f8288051"
        }
      ]
    }
  ]
}
