{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24711,
          "sha512": "e7f3d6e5264ea0cebe7b35aec3bebd7c9360768816152113f529cf59a46e452fb7f1e0ea7122a5682c8f1409a2869cd05d8c453415df92ebd2a7ccb882b0032f",
          "sha256": "399fe93b7d118b68c88d7f4bccf87d1f585f6f12f2988c4915e3d6616a7e59c8",
          "sha1": "601125ef1cc7cf71cc4d0fb9033066a9562e01ee",
          "md5": "9195d711325d6b156f529d0c5fc43cdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24711,
          "sha512": "e7f3d6e5264ea0cebe7b35aec3bebd7c9360768816152113f529cf59a46e452fb7f1e0ea7122a5682c8f1409a2869cd05d8c453415df92ebd2a7ccb882b0032f",
          "sha256": "399fe93b7d118b68c88d7f4bccf87d1f585f6f12f2988c4915e3d6616a7e59c8",
          "sha1": "601125ef1cc7cf71cc4d0fb9033066a9562e01ee",
          "md5": "9195d711325d6b156f529d0c5fc43cdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18314,
          "sha512": "9eff22767bfed3601e534fd3de45a0af4b996ba66016876245d33a644a58a319bc8bdaf03525076de06a7db230201ecc1e75f064bc676036ccabb2f95b155672",
          "sha256": "d017fc19fcb0ff642725eb4f5c1a9f8cfef4f5071fcae998c194d87cee02702d",
          "sha1": "21072359be606601e9a8b3dc9b34a2bb6eb71d11",
          "md5": "edecf73f36218c0cec4f716b268c4867"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160475,
          "sha512": "dda7c429d2bf68c051be53a4fd1b8c129b1892bf5275d0f7a3ba7e44f327e1d05c88c4812d54a8ef099a89f940c4c0324cee6ff56d7f9f6c6336d9983e2e90b8",
          "sha256": "8053455bd2e9557150ddf5ddd1b3bed1dba2865368e98289cc27ad0468a7ee0b",
          "sha1": "845b942a560aedc8a4e5c86c33c05188bb7fd2f7",
          "md5": "bd3c818bcac43dc303fa9cc0ec188cde"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
