{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24680,
          "sha512": "dd1204b54b8a3ea6f6865649f0f793400319052fd0b123355a058f99e7f0c121a538985d648b35c1580289b8cac04b1785beeab809cf956dadbcb8581938346a",
          "sha256": "d4fc4e916c4ba4d5de7222b5d2118ddfb18f5359897872760b8d8947eefd11f5",
          "sha1": "d2db8700e8cc728d378539567a6e2b014b718bd1",
          "md5": "a66b454189591ff7cc5d5654a2ad223b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24680,
          "sha512": "dd1204b54b8a3ea6f6865649f0f793400319052fd0b123355a058f99e7f0c121a538985d648b35c1580289b8cac04b1785beeab809cf956dadbcb8581938346a",
          "sha256": "d4fc4e916c4ba4d5de7222b5d2118ddfb18f5359897872760b8d8947eefd11f5",
          "sha1": "d2db8700e8cc728d378539567a6e2b014b718bd1",
          "md5": "a66b454189591ff7cc5d5654a2ad223b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18283,
          "sha512": "da2b60d63d346ecec51a11c4b70f00d09ece37e10d06077a5f9abb991029aca4ac759ced7c6c5368e4c891a1b085257ea6aec4f859580127e613e9f7299cc8ed",
          "sha256": "6476627e099ca7ccd7297cd0366763a85866f21fadb64e18b5ca06f292e53939",
          "sha1": "ce033a70c36b9fa3dfb5ea747156d87dd2b11f8f",
          "md5": "1307a066f34b8953a790d2f7be50c44f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160475,
          "sha512": "dda7c429d2bf68c051be53a4fd1b8c129b1892bf5275d0f7a3ba7e44f327e1d05c88c4812d54a8ef099a89f940c4c0324cee6ff56d7f9f6c6336d9983e2e90b8",
          "sha256": "8053455bd2e9557150ddf5ddd1b3bed1dba2865368e98289cc27ad0468a7ee0b",
          "sha1": "845b942a560aedc8a4e5c86c33c05188bb7fd2f7",
          "md5": "bd3c818bcac43dc303fa9cc0ec188cde"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
