{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24805,
          "sha512": "59edd452174cc873987ecd35c6dcb08dee83c635877819fce061d2708562d76a1e449b3b2a42b004affece6d22cb51202e46206f60948701e2f869edd4ae2a2c",
          "sha256": "9e7af8d374a84aa2f7d2f77902126855396128bc9a3cbb5d0d59d0167ecea75e",
          "sha1": "915942244615dc97bdcc91eeeefe22db69229590",
          "md5": "a71db2bc5eaf36fa69be762aa3946570"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24805,
          "sha512": "59edd452174cc873987ecd35c6dcb08dee83c635877819fce061d2708562d76a1e449b3b2a42b004affece6d22cb51202e46206f60948701e2f869edd4ae2a2c",
          "sha256": "9e7af8d374a84aa2f7d2f77902126855396128bc9a3cbb5d0d59d0167ecea75e",
          "sha1": "915942244615dc97bdcc91eeeefe22db69229590",
          "md5": "a71db2bc5eaf36fa69be762aa3946570"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18384,
          "sha512": "25f0e78aae7896d152476e821328dce5611c88298cc7adf280b35a8fd692ceeedba43de9e64e5f27e815a0b3437a40aa3b6e52d5d7ced3d8f38085d25bf6530a",
          "sha256": "4a83017f1da35f154da84b4b5bd9e7738b44338b9ae92f666217bca5556a89f3",
          "sha1": "c9aa50a217760efe35fb91429e6e6e88530e710c",
          "md5": "b0f204424ac4aea88d0cf02a1c5d3d46"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160649,
          "sha512": "e2a4d1da3ae2c7e199cd3cf85962698836db06b9ba3e5c8c0a3491a781ca86bb936b805f6eab557670b22972bf5ef28026fa81be41f967ddf7521d80ce600e81",
          "sha256": "eb83392d865234efb65cd7f2b7cafca1bd537d9be376468366a50420bd6ab28b",
          "sha1": "4bf8834c367599e237c99e46e1633282d6df95e5",
          "md5": "182fb6cc89f787a5a1586449221d4f10"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
