{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24490,
          "sha512": "7ecd78ea77df5e9321ed27e508fd828c039a40fa4d3210a127d9ce7fb8b0127a3dfc59703b51fa8d72036008b63ea6009c8e868591e10c10ee919fa53cd8d48a",
          "sha256": "ead76771a95747c5e7fc0e305682b5ce9588a0b02f63c2de43494a0cf554f88b",
          "sha1": "a6b65180d4824024c881ad73b19d9131713e50d8",
          "md5": "80dae4c552adcb39b13a69e57c33f233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24490,
          "sha512": "7ecd78ea77df5e9321ed27e508fd828c039a40fa4d3210a127d9ce7fb8b0127a3dfc59703b51fa8d72036008b63ea6009c8e868591e10c10ee919fa53cd8d48a",
          "sha256": "ead76771a95747c5e7fc0e305682b5ce9588a0b02f63c2de43494a0cf554f88b",
          "sha1": "a6b65180d4824024c881ad73b19d9131713e50d8",
          "md5": "80dae4c552adcb39b13a69e57c33f233"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18162,
          "sha512": "eee359f41383cd7416ff4c5c1cd56e8f9b65c467fb83ac4baf236d5a6fb42fba920c2e057cca589107c485bd12e55e56f7edbf10320dc3679bfe915ab6a1acf2",
          "sha256": "6ee22f7f3dbeba82bb1cabe4b2bcca8b3f37fa72e1f7bdffea2b3fb21099ab2f",
          "sha1": "f18855a65d1d74659a299305142ec68843989ac4",
          "md5": "6362a3b4117aa28fccbd8d786584bbd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 159989,
          "sha512": "a6bdeb91eb8fca7937c86f63402fb4e3e22b8662b4c4857ed75fe39df7206d127728a33ba261b5bff974c7de864d4e98e32c55080642395d1b83b9f65dbba71a",
          "sha256": "120bb8f173a32c852ca9399b47847e01932c0e760f748c7bb1ee8f0add23c986",
          "sha1": "29ce3230197323b7362c44b6e27de7d139588791",
          "md5": "3ad7c83e1622eb1d481f687f986fd94f"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
