{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24592,
          "sha512": "d61c6aeddaca9b7e17238579baced261aedf2ce3a3ceb87001a3a17f4a3fbfca6eade6e067388da81c5cae5a88ad19647abbb64d369b2da1ec49ae0191450704",
          "sha256": "96f8c823b00fc1c6f6cedf6c1092bee52a96b5638bf64d74737996711ec3f545",
          "sha1": "70d0e17d368a027697b7657ae7a77f4de43e3b27",
          "md5": "519a6caed18fac809cef3a3ca7d00dca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24592,
          "sha512": "d61c6aeddaca9b7e17238579baced261aedf2ce3a3ceb87001a3a17f4a3fbfca6eade6e067388da81c5cae5a88ad19647abbb64d369b2da1ec49ae0191450704",
          "sha256": "96f8c823b00fc1c6f6cedf6c1092bee52a96b5638bf64d74737996711ec3f545",
          "sha1": "70d0e17d368a027697b7657ae7a77f4de43e3b27",
          "md5": "519a6caed18fac809cef3a3ca7d00dca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18239,
          "sha512": "e2e6b7a1d59a34359293f87c3566c966eee06597cf552262872199a0316923e71f488a12ab2f38a4444f54b8e48ae8816f7443f4bdfd3a560c1364dd2e4de3bf",
          "sha256": "c32d44cf88397e79af19dfbfad00289b204f90cea6cd10758ec819d20b5b5714",
          "sha1": "8f65d6fbc31c7906d7ab466dcf723539637d8089",
          "md5": "767642adea00388b5e461a27c9b8fea3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160225,
          "sha512": "675dc10932fbc8054be70553b81a4b470a2ae25a8360b2bcb43718bb64af8f33620b4f0e46c0e37daec5bd0297b419d086c10635e02da86255e44053dcefc083",
          "sha256": "b5ca35d9fa9775851cbc5f9887ac426ba303a3a635c66057ac250b6ff4c40c94",
          "sha1": "53de76d03b78d4958f82a5de0300d2cc238b7863",
          "md5": "136a6a542ad3cb90f310949f15d12152"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
