{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-neoforge-1.21.1",
    "version": "21.1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24558,
          "sha512": "fc023299e7b2ab38d146cf049e14872b29f7c80eef74d57ad6201978e0700f33ec821a205b7c3b94ef731ddf1ebfe14fb8ba7d342d50ba2aecc5c1b957c9c9b9",
          "sha256": "28b164b2366e45d00173a914cb0172644ebad37d03587cfe63ea0b1e069a7df7",
          "sha1": "76bd21d20ebe2c74e9d85347be4f8eb08f778905",
          "md5": "dd27f1d7abc9bce338c07935f85b1e6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT.jar",
          "size": 24558,
          "sha512": "fc023299e7b2ab38d146cf049e14872b29f7c80eef74d57ad6201978e0700f33ec821a205b7c3b94ef731ddf1ebfe14fb8ba7d342d50ba2aecc5c1b957c9c9b9",
          "sha256": "28b164b2366e45d00173a914cb0172644ebad37d03587cfe63ea0b1e069a7df7",
          "sha1": "76bd21d20ebe2c74e9d85347be4f8eb08f778905",
          "md5": "dd27f1d7abc9bce338c07935f85b1e6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-sources.jar",
          "size": 18217,
          "sha512": "96483702812fdfa2022109710713e570ee9bd14773bb12ca47270135dd41526261dcbc0fa5369ee11d766c87ef33daf08bc69a56a883454eb4fffe9e1fc7533b",
          "sha256": "0adb7c25804b53e64455e78130c600c5e6a124540a630cdd3fd77d4829cdeb53",
          "sha1": "f08748f6e841f44a55d9eedd2d475eb61eb8ce03",
          "md5": "15a3b598dfbf900cca0d044675a9ebb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-javadoc.jar",
          "size": 160144,
          "sha512": "c4cb679890095d76a3426a25a231973d57062d391293944f34bdb283ff63fb2f4a2375807c72418dad85cc9395571235f9cbf2cd98e588fa581709eec8c5cfef",
          "sha256": "5f607740f78ccdbfcbefb662fb9b9b03c746d708c3e220f906943dd4b7a8d9d4",
          "sha1": "e8f784431a254dd680ba2dba926f0ae4299bf0a6",
          "md5": "9644c5d4469dd96db1399b8cd62c4ebc"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "url": "gk1hcore-neoforge-1.21.1-21.1.2.2-SNAPSHOT-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
