{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1henchants",
    "module": "gk1henchants-common-1.21.1",
    "version": "21.1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-common-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1henchants-common-1.21.1-21.1.1.1.jar",
          "url": "gk1henchants-common-1.21.1-21.1.1.1.jar",
          "size": 47008,
          "sha512": "d7cb1feb0a428bf1bc6cf38433fd3fd87baf1fd70893c83777c4b5b48f620b363b46fd0275e80bcfad790ccb41941e1f6603d066d556d2012902bcd49e600176",
          "sha256": "dd674a8228e04e60149e8ba71466dfb34cb270c7f21f59e7bb22b888409d32da",
          "sha1": "e44d6f4c1a21556b5470adec16dcfa49f9d12624",
          "md5": "42321906f23182d7629a4fd4c25376d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21+neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "universal-enchants",
          "version": {
            "requires": "v21.1.6-1.21.1-NeoForge"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1htags",
          "module": "gk1htags-common-1.21.1",
          "version": {
            "requires": "21.1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "gk1henchants-common-1.21.1-21.1.1.1.jar",
          "url": "gk1henchants-common-1.21.1-21.1.1.1.jar",
          "size": 47008,
          "sha512": "d7cb1feb0a428bf1bc6cf38433fd3fd87baf1fd70893c83777c4b5b48f620b363b46fd0275e80bcfad790ccb41941e1f6603d066d556d2012902bcd49e600176",
          "sha256": "dd674a8228e04e60149e8ba71466dfb34cb270c7f21f59e7bb22b888409d32da",
          "sha1": "e44d6f4c1a21556b5470adec16dcfa49f9d12624",
          "md5": "42321906f23182d7629a4fd4c25376d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1henchants-common-1.21.1-21.1.1.1-sources.jar",
          "url": "gk1henchants-common-1.21.1-21.1.1.1-sources.jar",
          "size": 19397,
          "sha512": "7a6579ee88a5b4e9f4cdea4667a8d0c49cb36fc2bb657066863fc21e3cc2dbc2f6c8af3035480d83df1dfd3f1feb35c60fe4418d537082b5966be5658c00537d",
          "sha256": "ba8ea1afd8641bfb3d44b39f621224bab9baba775c09851cc96aab2c2f4d41cf",
          "sha1": "cc8527304b99d91e1329a524bb515741dd58d864",
          "md5": "953cad0cff42c49846f130df8b3905db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1henchants-common-1.21.1-21.1.1.1-javadoc.jar",
          "url": "gk1henchants-common-1.21.1-21.1.1.1-javadoc.jar",
          "size": 120274,
          "sha512": "84a5907cc0e63cce66433228851d1cac386fe7edba8f6b4d00e60cc47a246a4d2325ab9a6095163e3c7bafd0be0192413637be3f11e80d059650381066c2e51f",
          "sha256": "d8a8e4890b8e6b9f560e6f439453b33a3883b63ba3c5ffdd9dcfb6aab7ce1352",
          "sha1": "425fa9c7a0673ecd38c15ae04d55c698eef91a1a",
          "md5": "6461b44f511abc48343905f42fbf4bc5"
        }
      ]
    }
  ]
}
