{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8.jar",
          "size": 14319,
          "sha512": "f377b7f8f007e6e712e585168a4e52e62ca6b39b4ea39b8ba72d0706c7df04b2c8be7ddf7c04abf91d407f1c6d5488e548c273de9da4a9ea24b12e4ac217b4ba",
          "sha256": "28a22b218f04598ef277179cd1ea001fd031769df6dbe2d179a7cf3baff6616b",
          "sha1": "c9ba975e541f5be88317e9c859680503abf0c1a1",
          "md5": "6736a081aae2ba34de439424a51c4693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8.jar",
          "size": 14319,
          "sha512": "f377b7f8f007e6e712e585168a4e52e62ca6b39b4ea39b8ba72d0706c7df04b2c8be7ddf7c04abf91d407f1c6d5488e548c273de9da4a9ea24b12e4ac217b4ba",
          "sha256": "28a22b218f04598ef277179cd1ea001fd031769df6dbe2d179a7cf3baff6616b",
          "sha1": "c9ba975e541f5be88317e9c859680503abf0c1a1",
          "md5": "6736a081aae2ba34de439424a51c4693"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-sources.jar",
          "size": 9094,
          "sha512": "f1817251a4de8f7ef754f1e273f88f4eee5135134c4ffe7ad1f515634d7079527be5202105483f82dae9b57a85d96a262448cc488167654d41c71568ab1096b0",
          "sha256": "59e92e21d1068d6f1a06088113313d3ceaaa2bc835e71172148127c1ee46e0f0",
          "sha1": "c3ae7bd4c1c0b520b4f2000c2f8a921736e53407",
          "md5": "99432b472b41f83783793a95f105ca92"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.8-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.8-javadoc.jar",
          "size": 129267,
          "sha512": "ca2403394e7ecb25f5f183bfe99587513b26126faf20e5b1d09d790b58a51ba740b6609c9f8570c73eca516a65e47fcd30aee950f22db63717192fe8c90a4e2a",
          "sha256": "d4c5a02573a2945d9bdcc1be9be9a82c4246da286a2f35d4ec3c444bab5b5708",
          "sha1": "641c68753be4bae8ae3fde3ed8ad22e06d50f5f1",
          "md5": "1f5584f472c8e0a61e9210b70c6418c5"
        }
      ]
    }
  ]
}
