{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.1.4-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2.jar",
          "size": 19178,
          "sha512": "16b9cfff70bacc6ada9fd2916041e3d1bb4ce86b7600787f881dd77779e15987249b4202e120ba9a14ca9c83f2abaa9d47fa8cd4eb9053e7f17be47624eac9d9",
          "sha256": "03315ff61961b1870ef353cfb63e7f0dfc6ed89707edadb7b7df3fb0b48adf67",
          "sha1": "d4f8fedf77daff311e14367add79eee7d6259757",
          "md5": "662deed5b6d2fd848e7cfa3deb98ce6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2.jar",
          "size": 19178,
          "sha512": "16b9cfff70bacc6ada9fd2916041e3d1bb4ce86b7600787f881dd77779e15987249b4202e120ba9a14ca9c83f2abaa9d47fa8cd4eb9053e7f17be47624eac9d9",
          "sha256": "03315ff61961b1870ef353cfb63e7f0dfc6ed89707edadb7b7df3fb0b48adf67",
          "sha1": "d4f8fedf77daff311e14367add79eee7d6259757",
          "md5": "662deed5b6d2fd848e7cfa3deb98ce6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2-sources.jar",
          "size": 13846,
          "sha512": "c1a3b19321c92703d5699e206cdffd4ab3193b715edbef027e996d5e0c2e8ddce0116554054304374294d16e18acb078661c55808a0000c1bd94782856d3958b",
          "sha256": "db0afec198de8613f3518a758ebd4d3db7dc623308999b799bcfd94c938948fb",
          "sha1": "d05744a70cd85234f4ed4368250095bd00842366",
          "md5": "ac3621034687a863f2e5d72365130690"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.1.4-beta2-javadoc.jar",
          "size": 123362,
          "sha512": "08b6c75df35749c64ac23f61a3a577403c83c30510bb3ab2d0c0054b61108e482a7373683e18d9cc237283ce9f065b4244e84437466160df8e1200387aed70b0",
          "sha256": "aa33be979b63a4cc3fca96ff1299b7c41f6af118614b271a2a65871056ccdfc3",
          "sha1": "227dce7002d537614edb98f3cb50ccfe1aa5f74d",
          "md5": "35b61e62c80edf0602762c317bc46d1f"
        }
      ]
    }
  ]
}
