{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.4-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta1.jar",
          "size": 13509,
          "sha512": "dd45541c6d55600a6976d53dd7154de50c0f2bbb7232f7fdba364494d4ade2e2ae985649fb65d06d5beef311cc428aaaeb4ab262c061c92ceceecd0dc985d2cf",
          "sha256": "85a24398cdd23d3271aa2e106b97cac0f55e76257ce15c3dbdb71a3595afa8dc",
          "sha1": "0f17331fab018d237bfcc4f22ac708c4dad70e2a",
          "md5": "4bb387312baf329ffb695b140a248809"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta1.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta1.jar",
          "size": 13509,
          "sha512": "dd45541c6d55600a6976d53dd7154de50c0f2bbb7232f7fdba364494d4ade2e2ae985649fb65d06d5beef311cc428aaaeb4ab262c061c92ceceecd0dc985d2cf",
          "sha256": "85a24398cdd23d3271aa2e106b97cac0f55e76257ce15c3dbdb71a3595afa8dc",
          "sha1": "0f17331fab018d237bfcc4f22ac708c4dad70e2a",
          "md5": "4bb387312baf329ffb695b140a248809"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta1-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta1-sources.jar",
          "size": 9757,
          "sha512": "1ccdf72ffdb5c35f3b1990c4fadcb326b7149f5513aa00976ebb39eb9ca77c20f87a0b22c4123699bab0f4b6fec8f2a7cad2d31873fcd8922c16bc6af4755c37",
          "sha256": "7959bfb3cea757788a1dfd795516696d4fdb28273a6762d6dd360aee82740354",
          "sha1": "080a2ce5a91df73e4ed436ec2c04987b22730ba5",
          "md5": "38031a072a62f0485cdeeb2f58ab72de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta1-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta1-javadoc.jar",
          "size": 114235,
          "sha512": "c34ccc8f32e9c7f078d4488eae46818df36a1bc1df150e158efce4824c87cba48dce25b081786c1c69f43ec88261303432068264daf4b57cf18bcf90e662dca6",
          "sha256": "f97a6a107cc927d3a46c168f84cfb8284c926bd0e833d16ce4e5ce41edf26b94",
          "sha1": "d55595e62763705a566e6453bde587efc6f7ef3c",
          "md5": "dbea7e48b20798a2fb99fbfc78d8803b"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.4-beta1-accesstransformer.cfg",
          "url": "gk1hcore-common-1.21.1-21.1.1.4-beta1-accesstransformer.cfg",
          "size": 78,
          "sha512": "b5fd5d161d7ffbffff9376a3a8f54403bf912b280fa9e3a8112ca57ec1cfee9e61cbcd86e6a7c712c913c8baa024dfaa5c9b3f9bb5a62b5dd2e9287129c2686c",
          "sha256": "02a7ee6b9212debbab05bfe5b7e1325e239fd7abd569d318a0391153040c3475",
          "sha1": "284ca492085fea4bd951f4bbff99326bc89d742e",
          "md5": "26ff850e5bd778d05d3b434990153748"
        }
      ]
    }
  ]
}
