{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-fabric-1.21.1",
    "version": "21.1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.0.jar",
          "size": 23056,
          "sha512": "cbe3b85b82063098e3f8f6b64fc496a285882a81c7df8c5a46a37ce108596b4e3e311f815a141d93122ba411ad22316d7cba88be605894f9a38f100771f581c7",
          "sha256": "243fb9f86749c959386972ff142145e0dc9f56503de301b977cfb24a05324dda",
          "sha1": "83cd4dc84404a462cd57eb0d2c814f339a8a7149",
          "md5": "e5bb0280484ae5cd41ceb340fd3c0521"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.0.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.0.jar",
          "size": 23056,
          "sha512": "cbe3b85b82063098e3f8f6b64fc496a285882a81c7df8c5a46a37ce108596b4e3e311f815a141d93122ba411ad22316d7cba88be605894f9a38f100771f581c7",
          "sha256": "243fb9f86749c959386972ff142145e0dc9f56503de301b977cfb24a05324dda",
          "sha1": "83cd4dc84404a462cd57eb0d2c814f339a8a7149",
          "md5": "e5bb0280484ae5cd41ceb340fd3c0521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.0-sources.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.0-sources.jar",
          "size": 17521,
          "sha512": "b4563b59a3f1a0dc3b5d7ece6f0a180b592c6d14d102f5eb49d3d23b73cb9b9964a7e54ec9ea3c65275ba0de92f242dab87a8394efc705844cdeae687e116bf8",
          "sha256": "55cb8d5e05be442aef9c1370c68d24a7df38c54a56dea71d6c5c3ca92a7b0196",
          "sha1": "32d5ff0a4c4fe36847547483fed87d5a39433a32",
          "md5": "2a737b4b8b0523a0970ffd8c6f3717c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-fabric-1.21.1-21.1.2.0-javadoc.jar",
          "url": "gk1hcore-fabric-1.21.1-21.1.2.0-javadoc.jar",
          "size": 153653,
          "sha512": "405ae07a92aca6ee8539c3dcda86f78512c859104fa5fac3bc7b5512aca6f240f58254cccca3538de3b419552828c722a27f6142688dbdb7a592c7911f3ba0b1",
          "sha256": "c4d83d26f34faa9c079e81215073d3d258e2f74d6348a1d5bce4d1e0d76025b8",
          "sha1": "529855745932641c17d7479ecb3f4d7b4cdc534c",
          "md5": "56950d6e45e57a8c56a20db0f03a8269"
        }
      ]
    }
  ]
}
