{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hextras",
    "module": "gk1hextras-fabric-1.21.1",
    "version": "21.1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "size": 16451,
          "sha512": "0c95622b988a537a54169432368b43f79445226577560b546c7b323387b92ca130c986faeb620a00726f41641faaf7ce93290db17363fcd535544131b21dc660",
          "sha256": "a6c0fc9ff988b8f7da65cb8227069bdfc4091558bbd1b494992c63d4cb5a9dc3",
          "sha1": "d8db105441a6a0e20194e8c98352db226dba066a",
          "md5": "7af1abc98cb1eb3c36a04bd7fefcda81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.4+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sword-blocking-mechanics",
          "version": {
            "requires": "v21.1.1-1.21.1-Fabric"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "21.1.39"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ender-zoology",
          "version": {
            "requires": "v21.1.4-1.21.1-Fabric"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "size": 16451,
          "sha512": "0c95622b988a537a54169432368b43f79445226577560b546c7b323387b92ca130c986faeb620a00726f41641faaf7ce93290db17363fcd535544131b21dc660",
          "sha256": "a6c0fc9ff988b8f7da65cb8227069bdfc4091558bbd1b494992c63d4cb5a9dc3",
          "sha1": "d8db105441a6a0e20194e8c98352db226dba066a",
          "md5": "7af1abc98cb1eb3c36a04bd7fefcda81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1-sources.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1-sources.jar",
          "size": 13090,
          "sha512": "81a7d9929a9655aaa78cbb36bbdd7ae514c77f63855422d6c40e9a5d7b2bd12786e1f702743ffbf1958d1b353686667fb93e78a266ad55fa640b438296b45380",
          "sha256": "56dc01ec9ec9ad311a5b4021e491d71c786c49efb54457bbc09d03ff5a6c9cc4",
          "sha1": "6fea72d4dd20a3f5850f25d7c4a60c7844e25eed",
          "md5": "f0f2e5225d4bc18a9fdc57d68252aa39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1-javadoc.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1-javadoc.jar",
          "size": 116617,
          "sha512": "631ce52252dcd4429029594781bd33d1ffd2d6d33a465b2de31e98a49300ad25d8d75e77ba7255144b100175144dca093a67516a6d479d151e34e6ad1affd7eb",
          "sha256": "351fbc5d3810e2187fcf27d0c7a08b6a06870daf63be69eeb796c2b09224c564",
          "sha1": "516ac4993cb6811823cb55b7bd5874ee7743f91e",
          "md5": "e95b0df361e70ff1e4a78b7852d7261b"
        }
      ]
    }
  ]
}
