{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hextras",
    "module": "gk1hextras-fabric-1.21.1",
    "version": "21.1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "size": 16448,
          "sha512": "f3a03fe8804b1458b9fe89ddb077db8f5cf9c6dd203c0a448cdb89afb53f12c7ff01e2bc688cf3c5fb9c115f6c111b98a61cd57496710cf9632f97782ba69e7e",
          "sha256": "33f148c826bd3296abdaedf0179ee1bc3e506c6c148de74b7166a52fd475d004",
          "sha1": "a4cb5b3e95ca7ff7d3e345fa7706f909ac6dd53d",
          "md5": "3d718e4ec9c73ba717efdd9362a6bf3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-fabric-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.3+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ender-zoology",
          "version": {
            "requires": "v21.1.4-1.21.1-Fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "sword-blocking-mechanics",
          "version": {
            "requires": "v21.1.1-1.21.1-Fabric"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "21.1.39"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1.jar",
          "size": 16448,
          "sha512": "f3a03fe8804b1458b9fe89ddb077db8f5cf9c6dd203c0a448cdb89afb53f12c7ff01e2bc688cf3c5fb9c115f6c111b98a61cd57496710cf9632f97782ba69e7e",
          "sha256": "33f148c826bd3296abdaedf0179ee1bc3e506c6c148de74b7166a52fd475d004",
          "sha1": "a4cb5b3e95ca7ff7d3e345fa7706f909ac6dd53d",
          "md5": "3d718e4ec9c73ba717efdd9362a6bf3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1-sources.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1-sources.jar",
          "size": 13088,
          "sha512": "3b5cdf1df877b61dd028cb3afe47b051289d40061a277c6102dc8c48905073ca9104ef3a928d2d15adcc715d663b614acb41fade571a23b337c5b89f59942adc",
          "sha256": "bf6ceb152a3f3c3240ac70e0f374e5d893c52619f23f6374844a7f8e7cdf48bc",
          "sha1": "b0dfd784e78a1727b0bd4d4494a072fb95018bbb",
          "md5": "5737adfd87dfdaebf1003d5cbf6fefd0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-fabric-1.21.1-21.1.1.1-javadoc.jar",
          "url": "gk1hextras-fabric-1.21.1-21.1.1.1-javadoc.jar",
          "size": 116616,
          "sha512": "7aacb42dd8737742d355b819b1725d388c33653150321dc61d4d645b49dc1d04f517de1e0c7092c9e223321211d8f8ae8a5a7db65668976c0c967ce79072db84",
          "sha256": "964ca7b08787c27036b85a809dcef838ebef767159c0687b6c0fc6936d984c5e",
          "sha1": "192fc31e4b1c32ed09b885c15b21530db37bc0ce",
          "md5": "00dd763d1a2280d410517ba520644ded"
        }
      ]
    }
  ]
}
