{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hextras",
    "module": "gk1hextras-common-1.21.1",
    "version": "21.1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-common-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-common-1.21.1-21.1.1.1.jar",
          "size": 11618,
          "sha512": "cc29cf5477e82ed726bee427869d663779a2a22bfdd121c5548f843b8171d8d0a2149a8d02b1e54a6987f4f4eb4bceadbbd0e325fabf40aeb478ab17c99ac8d4",
          "sha256": "d7c0b25681d3389a61d04c3056e57c11400cd1c8f7616929b251db35214adef1",
          "sha1": "deb072f4c059c38afbcc5170f6760eb67e9d97bf",
          "md5": "df0c1d6284822dafd6b8a54f4601bff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.fzzyhmstrs",
          "module": "fzzy_config",
          "version": {
            "requires": "0.7.4+1.21+neoforge"
          }
        },
        {
          "group": "io.github.gameking1happy.gk1hcore",
          "module": "gk1hcore-common-1.21.1",
          "version": {
            "requires": "21.1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hextras-common-1.21.1-21.1.1.1.jar",
          "url": "gk1hextras-common-1.21.1-21.1.1.1.jar",
          "size": 11618,
          "sha512": "cc29cf5477e82ed726bee427869d663779a2a22bfdd121c5548f843b8171d8d0a2149a8d02b1e54a6987f4f4eb4bceadbbd0e325fabf40aeb478ab17c99ac8d4",
          "sha256": "d7c0b25681d3389a61d04c3056e57c11400cd1c8f7616929b251db35214adef1",
          "sha1": "deb072f4c059c38afbcc5170f6760eb67e9d97bf",
          "md5": "df0c1d6284822dafd6b8a54f4601bff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-common-1.21.1-21.1.1.1-sources.jar",
          "url": "gk1hextras-common-1.21.1-21.1.1.1-sources.jar",
          "size": 9683,
          "sha512": "29621e78467dd12baa293d0736a91ddc24e698700ce08aa8445ccb2fd803894090fa3acac028e1b162d7e33c063c646ffbf996df52a6e9b6a29569917a9e6189",
          "sha256": "cf0c518999af2a21fa030b30072dc2a7eae8d12b293326616bc31ade76d04f2c",
          "sha1": "29c0c188ba1dc2f3602fb112fadc7f43d0fc92a1",
          "md5": "754d13ff5cdd7fa923075e72bcdd4d49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hextras-common-1.21.1-21.1.1.1-javadoc.jar",
          "url": "gk1hextras-common-1.21.1-21.1.1.1-javadoc.jar",
          "size": 108276,
          "sha512": "b355e5a05882137057d225e7d931694ea935e9199900d84c4098a15c9f8a4aaabdc00d058c2977668700bb1ae16cde4481d75242f5deea7d58cee93cf0e78505",
          "sha256": "213e395ed821522ceff4d4585c68d6b947113786cebd4af6907298820e252255",
          "sha1": "5f378cd05cde31a53762e2268abdc1e376fd5216",
          "md5": "cfc170b6ad5aed9ea779936e260fcb47"
        }
      ]
    }
  ]
}
