{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gameking1happy.gk1hcore",
    "module": "gk1hcore-common-1.21.1",
    "version": "21.1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3.jar",
          "size": 9753,
          "sha512": "0ae2bf4aaafbe17102f80b6fcbd263df1001e076ca02be1b496a1351062b7efd492a392b58a0fdbe9385fde481b0b9d9c6d9fd423667956bf923719e36c48518",
          "sha256": "7f881f30b6fbe660211732816619ed9a9a7bb45083358c84beb027268b9d8a8e",
          "sha1": "31068bc6b3b7296bd264116fa19121d5d89d249d",
          "md5": "de27217319b1329dd3523adc97ddac39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3.jar",
          "size": 9753,
          "sha512": "0ae2bf4aaafbe17102f80b6fcbd263df1001e076ca02be1b496a1351062b7efd492a392b58a0fdbe9385fde481b0b9d9c6d9fd423667956bf923719e36c48518",
          "sha256": "7f881f30b6fbe660211732816619ed9a9a7bb45083358c84beb027268b9d8a8e",
          "sha1": "31068bc6b3b7296bd264116fa19121d5d89d249d",
          "md5": "de27217319b1329dd3523adc97ddac39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-sources.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-sources.jar",
          "size": 7244,
          "sha512": "65302872dbceba11c0fcc18bed9cded06a0becd548346af83db9da1bb1d55fce62142efbb188ced7eb7a47bf3b32d04fc54c5a6a1c8cda9adb2c827fd5aa73b1",
          "sha256": "72faa1a64c80dbd01146a094f116ee2b904cb3600aa26d359733b7a600dcd9a6",
          "sha1": "9bf1f4f06426ab7a6e89ed8c2a38ee9c7d695d37",
          "md5": "6de2f1c084e65fbb9f8e3efc3444b208"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gk1hcore-common-1.21.1-21.1.1.3-javadoc.jar",
          "url": "gk1hcore-common-1.21.1-21.1.1.3-javadoc.jar",
          "size": 107588,
          "sha512": "aa5e082a3331f8a79e504e7fc61baf73217f0ffa0dd4d0807372178f5845f1eb076e0b13e9d1cc755c711e6cbe9baf92043f7519dc28c9a4c3f11de45b6b0e0a",
          "sha256": "a979f915d9e9bbbd2ef6972abd0738194414caa25df09f641e0bff930c156ea4",
          "sha1": "127f75a93d2f6a495acf662467666ba3ed045806",
          "md5": "ecd34df5cefb075d4cb2ec2100527efa"
        }
      ]
    }
  ]
}
